README.md
Some of the text in the README was missing a space between the # and the text
=> Put space between # and header text

auth-service/build.gradle, auth-service/src/main/java/com/petclinic/auth/Role/Role.java, auth-service/src/main/java/com/petclinic/auth/Role/RoleController.java, auth-service/src/main/java/com/petclinic/auth/Role/RoleIDLessDTO.java, auth-service/src/main/java/com/petclinic/auth/Role/RoleService.java, auth-service/src/main/java/com/petclinic/auth/Role/RoleServiceImpl.java, auth-service/src/main/java/com/petclinic/auth/User/User.java, auth-service/src/test/java/com/petclinic/auth/AuthServiceApplicationTests.java, auth-service/src/test/java/com/petclinic/auth/AuthServicePersistenceTests.java, auth-service/src/test/java/com/petclinic/auth/AuthServiceRoleControllerTests.java, auth-service/src/test/java/com/petclinic/auth/AuthServiceRoleRepoTests.java, auth-service/src/test/java/com/petclinic/auth/AuthServiceRoleServiceTests.java
- Made sure RoleController calls RoleService and not RoleRepo directly
- Added JaCoCo for coverage reports and setup a 90% minimum coverage to pass tests
- Refactored each test type into its own file for readability and (my own) sanity
- Made sure to get 100% coverage
=> bug(AUTH-CPC-160): use role service instead of repo

billing-service/build.gradle, billing-service/src/main/java/com/petclinic/billing/datalayer/BillDTO.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java
=> feat(BILL-CPC-74) : basic tests

api-gateway/src/main/resources/static/scripts/visits/visits.controller.js, api-gateway/src/main/resources/static/scripts/visits/visits.template.html, visits-service/src/main/resources/schema-mysql.sql
Previous visits would no longer display on the UI once we switched to 3 layer architecture .
=> feat( VISE-CPC-99) : fixed visits html so it displays visits , added a visits controller

billing-service/build.gradle, billing-service/src/main/java/com/petclinic/billing/datalayer/BillDTO.java, billing-service/src/main/java/com/petclinic/billing/http/BillControllerExceptionHandler.java, billing-service/src/main/java/com/petclinic/billing/http/HttpErrorInfo.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java
Reverted the Removal of:
- BillControllerExceptionHandler (Nam)
- BillServiceImplTest (Randy)
- HttpErrorInfo (Nam)
Reverted Changes made to:
- BillDTO (Justin)
- build.gradle (Randy)
Co-Authored by Tristan
=> Bug(BILL): Revert Rollback Changes

api-gateway/src/main/resources/static/scripts/vet-details/vet-details.js, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.template.html, vets-service/src/main/java/com/petclinic/vets/businesslayer/VetService.java, vets-service/src/main/java/com/petclinic/vets/businesslayer/VetServiceImpl.java, vets-service/src/main/java/com/petclinic/vets/presentationlayer/VetResource.java, vets-service/src/test/java/com/petclinic/vets/presentationlayer/VetResourceTest.java
Finished enable vet, added the test and the ui.
UI will have to wait for APIG.
Curl commands work
=> Feat(VETS-CPC-63): Enable Vet

visits-service/build.gradle
Added dependency for Swagger UI in build.gradle
=> conf(VISE-CPC-216): Added dependency for Swagger UI

customers-service/build.gradle
Added JaCoCo for the test coverage of Customers Service.
=> conf(CUST-CPC-264): Add Jacoco

api-gateway/src/main/resources/static/scripts/vet-form/vet-form.controller.js, api-gateway/src/main/resources/static/scripts/vet-form/vet-form.template.html, vets-service/src/main/java/com/petclinic/vets/datalayer/DataValidation.java, vets-service/src/main/java/com/petclinic/vets/datalayer/Specialty.java
Did the maximum of Data Validation possible within the front-end (vet-form.html).
Limited verification is doable with AngularJS.
Back-End verification covers more ground for the data clean/verification.
=> Feat(VETS-CPC-231): Front-End Data Validation

api-gateway/src/main/resources/static/css/visitsCalendarStyle.css, api-gateway/src/main/resources/static/scripts/visits/visits.controller.js, api-gateway/src/main/resources/static/scripts/visits/visits.template.html
Added a feature to see the availabilities of the different vets depending on their workdays on the calender UI. The user can select a specific practitionner from the dropdown list to get a specific schedule from a vet.
In addition, I refactored some methods so that they take less space in the code and deleted duplicates to make it moe efficient.
I removed unhelpful comments as well and fixed some CSS issues related to the implementation of this feature.
=> Feat(VISE-CPC-175): Vet availability input in Calendar UI

billing-service/src/main/java/com/petclinic/billing/datalayer/Bill.java, billing-service/src/main/java/com/petclinic/billing/datalayer/BillDTO.java, billing-service/src/main/resources/data-h2.sql, billing-service/src/main/resources/data-mysql.sql, billing-service/src/main/resources/db/hsqldb/data.sql, billing-service/src/main/resources/db/hsqldb/schema.sql, billing-service/src/main/resources/db/mysql/data.sql, billing-service/src/main/resources/db/mysql/schema.sql, billing-service/src/main/resources/schema-h2.sql, billing-service/src/main/resources/schema-mysql.sql, billing-service/src/test/java/com/petclinic/billing/BillingServiceApplicationTests.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java, billing-service/src/test/java/com/petclinic/billing/datalayer/BillServicePersistenceTests.java
In this pull request I added customerBillId to everything that needed it
=> feat(BILL-CPC-249):Add customerId to Database and Bill Object

api-gateway/Dockerfile, auth-service/Dockerfile, billing-service/Dockerfile, customers-service/Dockerfile, vets-service/Dockerfile, visits-service/Dockerfile
Sorry Christine I was too lazy to commit after each service but the fix is there enjoy everyone!
=> Feat(VETS-CPC-335): Dockerfiles Error Fix For All Services

mailer-service/mailer/service/mailer.service.go
- Fixed e-mail body being set as header instead of body
=> bug(MAIL-CPC-359): E-mail body not sending

api-gateway/src/main/resources/static/scripts/owner-details/owner-details.controller.js, api-gateway/src/main/resources/static/scripts/owner-details/owner-details.template.html, api-gateway/src/main/resources/static/scripts/owner-list/owner-list.template.html, customers-service/src/main/resources/data-h2.sql, customers-service/src/main/resources/data-mysql.sql, customers-service/src/main/resources/schema-h2.sql, customers-service/src/main/resources/schema-mysql.sql
Fixed the table not been created for Customer Service
=> bug(CUST-CPC-367): Fixing Owner Table

.gitignore, api-gateway/src/main/java/com/petclinic/bffapigateway/BFFApiGatewayApplication.java, api-gateway/src/main/java/com/petclinic/bffapigateway/config/GlobalExceptionHandler.java, api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Register.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Role.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/UserDetails.java, api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/GenericHttpException.java, api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/HttpErrorInfo.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/java/com/petclinic/bffapigateway/utils/Rethrower.java, api-gateway/src/main/resources/static/scripts/auth/signup/signup-form.controller.js, api-gateway/src/main/resources/static/scripts/auth/signup/signup-form.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, auth-service/src/main/resources/application.yml, docker-compose.yml
- Added exception handler to gateway
- Fixed create user invoking wrong URL
- Fixed create user not sending body
- Fixed create user not calling correct service method
- Added Rethrower helper class for my own sanity (fuck Mono)
- Added GenericHttpException & HttpErrorInfo
- Added Register DTO
- Added missing auth client service tests
- Fixed sign up controller making a useless get request
- Fixed sign up controller's `add` not being called
- Fixed sign up controller's `$scope.signup` not aligning with the template (signup VS newUser)
- Added (soft) redirect to login page after successful register
- Added error display on unsuccessful register
=> feat(APIG-CPC-354): Integrate register

customers-service/src/test/java/com/petclinic/customers/presentationlayer/ExceptionsTests.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-403
Created all tests for the HttpErrorInfo class to greatly improve our code coverage
I did not change anything but rather added 2 tests to the ExceptionsTests class in the Customer Service tests folder. These 2 tests cover the 6 necessary pieces of code that jacoco wanted us to cover in this class. Our code coverage for this class is now 100%. Please go over the code and observe the attached screenshots!
=> feat(CUST-CPC-403):Created all necessary tests for HttpErrorInfo class thus, increasing code coverage

api-gateway/src/main/resources/static/scripts/auth/login-form/login-form.template.html
JIRA: https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/16?modal=detail&selectedIssue=CPC-489&quickFilter=29
- fixed the clear text password to make it work in all browsers
- only added a <i> tag to the UI
- Used javascript onclick function
CHROME:
EDGE:
=> bug (AUTH-CPC-489): clear text pwd that works in all browsers

api-gateway/src/main/resources/static/scripts/visits/visits.controller.js, api-gateway/src/main/resources/static/scripts/visits/visits.template.html
JIRA: [CPC-491](https://champlainsaintlambert.atlassian.net/browse/CPC-491?atlOrigin=eyJpIjoiNzRlMTA4ZTE1OTQ0NDk2ZGFlOTZhNGE0ODA4NDRkNTkiLCJwIjoiaiJ9)
There was a bug found that when editing a visit, the wrong date would be sent and instead of the date picked, the current date would be sent. While fixing this I noticed that the new status field was not being sent as well so added that also. 
- Fixed the data being sent when doing a pull request to now properly send the date that was selected.
- Also noticed that the status was not being sent when editing a visit so added that as well
=> bug(VISE-CPC-491): Fixed bug where incorrect data would be sent when editing a visit

visits-service/src/main/java/com/petclinic/visits/businesslayer/VisitsService.java, visits-service/src/main/java/com/petclinic/visits/businesslayer/VisitsServiceImpl.java, visits-service/src/main/java/com/petclinic/visits/presentationlayer/VisitResource.java, visits-service/src/test/java/com/petclinic/visits/businesslayer/VisitsServiceImplTests.java, visits-service/src/test/java/com/petclinic/visits/datalayer/PersistenceTests.java, visits-service/src/test/java/com/petclinic/visits/presentationlayer/VisitResourceTest.java
JIRA: [CPC-496](https://champlainsaintlambert.atlassian.net/browse/CPC-496?atlOrigin=eyJpIjoiMjBkMjA0ZTEyZWE1NDUyMjlhN2Q4MWIxNmZhYzUwN2IiLCJwIjoiaiJ9)
In some of our features with UI, we change or edit information about 1 visit only. Instead of reloading information about every visit, It would probably be best if we request the 1 visit instead of all of them.
- Made tests for the new code that will be written in the 3 layers.
- Added a new mapping in the Presentation Layer to request 1 visit 
- Added required methods in the business layer
=> feat(VISE-CPC-496): Get a Single Visit by Visit ID

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/VisitDetails.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-332
This ticket will implement the request to get scheduled visits of a pet and also the corresponding mapping in the API gateway controller.
Added the method in the VisitsServiceClient.
Added the mapping in the BFFApiGatewayController.
Added Controller Testing.
Added Integration Testing.
No changes have been made to the UI.
=> feat(APIG-CPC-332): Get request for scheduled visits of a pet

test_all.bash
Added the test_all.bash file and added the host and port. It is ready to be used once the aggregates are created.
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-501?atlOrigin=eyJpIjoiMTBjYmJlOThiNWIyNDgyMjg1ZjA5ZTEyZDc3OTM1NTUiLCJwIjoiaiJ9
Added a file called test_all.bash so that my teammates can write their tests once they are done with the aggregate class.
=> FEAT(APIG-CPC-501) Create test_all.bash

njs/owners.js
=> conf(NULL-CPC-NULL): Fixed DELETE not going through singleAggregation

docker-compose.yml
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-634
This ticket is because we had a conflict in the docker-compose.yml and so we're creating 2 different hosts for the billing and vet services
- changed docker-compose.yml to include 2 mongo hosts
- changed the ports to run on different ports
=> (bug/VVS-CPC-634) fix docker conflict

auth-service/src/main/resources/application.yml
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-628?atlOrigin=eyJpIjoiZWQ3NGI3YWVmMmZiNGExZGJkYWJlNDg0OGU3MTU2YWYiLCJwIjoiaiJ9
The registration of new users was impossible as the Validation of a new user email would always fail.
Now, the email sent to the registering user will be correct and call the right gateway method to actually validate the user.
The user will now be able to sign in!
Api Gateway origin was adjusted to the correct one.
No UI changes where made, but you can now log in and it looks like so:
=> feat(ACMS-CPC-628): Fix User Validation

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/VetDTO.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java
JIRA: (https://champlainsaintlambert.atlassian.net/browse/CPC-638)
The testing for the controller methods were done but not the integration tests for the VetsServiceClient
- created the VetsServiceClientIntegrationTests class
- created all tests
- changed vetsServiceClient to have a setter for the url
- added a no-args constructor for the dto
- all tests passes jacoco
=> feat(VVS-CPC-638): DomainClientLayer testing done

api-gateway/src/main/resources/static/scripts/owner-details/owner-details.template.html, api-gateway/src/main/resources/static/scripts/vet-list/vet-list.template.html
JIRA: [Jira Ticket](https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/40?modal=detail&selectedIssue=CPC-614&assignee=631f346fcf721d09b015d1b4)
UI modification on the owner detail page to make buttons more visible.
- Buttons are reactive
- Button for the edit method is blue
- Buttons for the add methods are green
- Buttons for the delete methods are red
**Before:** 
**After:** 
- Colors are hard coded
=> Button updates to the owner-details page

api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/BillDetails.java, api-gateway/src/main/resources/static/scripts/bill-form/bill-form.controller.js, api-gateway/src/main/resources/static/scripts/bill-form/bill-form.template.html, api-gateway/src/main/resources/static/scripts/bill-history/bill-history.template.html, billing-service/src/main/java/com/petclinic/billing/datalayer/Bill.java, billing-service/src/main/java/com/petclinic/billing/datalayer/BillDTO.java, billing-service/src/main/java/com/petclinic/billing/datalayer/DataSetupService.java
https://champlainsaintlambert.atlassian.net/browse/CPC-630
Before:
After:
=> Feat/bill cpc 630 upgrade UI form to include vets and upgrade minor details on the form

customers-service-reactive/src/main/java/com/petclinic/customersservice/business/DataSetupService.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/business/OwnerService.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/business/OwnerServiceImpl.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/business/PetService.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/business/PetServiceImpl.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/data/Pet.java, customers-service-reactive/src/test/java/com/petclinic/customersservice/business/OwnerServiceImplTest.java, customers-service-reactive/src/test/java/com/petclinic/customersservice/business/PetServiceImplTest.java, customers-service-reactive/src/test/java/com/petclinic/customersservice/business/PhotoServiceImplTest.java, customers-service-reactive/src/test/java/com/petclinic/customersservice/exceptions/HttpErrorInfoTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-690
Add Insert photo and DataSetupService for photo
Add DataSetupService for photo
=> feat(ACMS-CPC-690) Insert photo

customers-service-reactive/src/main/java/com/petclinic/customersservice/business/PetTypeService.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/business/PetTypeServiceImpl.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/data/PetTypeRepo.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/presentationlayer/PetTypeController.java, customers-service-reactive/src/test/java/com/petclinic/customersservice/business/PetTypeServiceImplTest.java, customers-service-reactive/src/test/java/com/petclinic/customersservice/presentationlayer/PetTypeControllerIntegrationTest.java, docker-compose.yml
JIRA: 
https://champlainsaintlambert.atlassian.net/browse/CPC-589
Get all petTypes functionality was added.
- Method added to PetTypeService and PetTypeServiceImpl;
- Controller with method added;
- Relevant tests added (Controller Integration & Service).
=> feat(ACMS-CPC-589) Get All Pet Types

api-gateway/src/main/resources/static/scripts/vet-list/vet-list.controller.js, api-gateway/src/main/resources/static/scripts/vet-list/vet-list.template.html
[JIRA: link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-639)
we made this ticket to fix the filtering problem in the API to show active/inactive
- made changes to the controller to use the endpoints in the API controller instead of the filtering method
- changes the HTML of the dropdown to reflect the new code
=> feat(VVS-CPC-639): Fix Filtering For Active/Inactive in Vet List

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/BillServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillService.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillServiceImpl.java, billing-service/src/main/java/com/petclinic/billing/datalayer/BillRepository.java, billing-service/src/main/java/com/petclinic/billing/datalayer/DataSetupService.java, billing-service/src/main/java/com/petclinic/billing/presentationlayer/BillResource.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java, billing-service/src/test/java/com/petclinic/billing/datalayer/BillServicePersistenceTests.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceIntegrationTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceUnitTest.java
* get bills by vet id + tests
* get bills by vet id tests
* get bills by vet id implemented in api gateway
* tests fixed
=> Feat/bill/cpc 653 get bills by vet (#332)

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/BillServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillService.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillServiceImpl.java, billing-service/src/main/java/com/petclinic/billing/datalayer/BillRepository.java, billing-service/src/main/java/com/petclinic/billing/presentationlayer/BillResource.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java, billing-service/src/test/java/com/petclinic/billing/datalayer/BillServicePersistenceTests.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceIntegrationTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceUnitTest.java
* delete by vet id implemented in the service
* Feat/bill/cpc 653 get bills by vet (#332) (#337)
* get bills by vet id + tests
* get bills by vet id tests
* get bills by vet id implemented in api gateway
* tests fixed
* tests
* service tests implemented and passed
* api gateway method and tests
=> Feat/cpc/bill cpc 535 delete all bills by vet (#338)

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/BillServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/css/ownerdetail.css, api-gateway/src/main/resources/static/scripts/owner-details/owner-details.controller.js, api-gateway/src/main/resources/static/scripts/owner-details/owner-details.template.html, api-gateway/src/main/resources/static/scripts/owner-list/owner-list.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, auth-service/src/main/java/com/petclinic/auth/User/UserServiceImpl.java, auth-service/src/main/resources/db/migration/V1.1__Add_roles_table.sql, auth-service/src/test/java/com/petclinic/auth/e2e/User/AuthServiceE2ETests.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillService.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillServiceImpl.java, billing-service/src/main/java/com/petclinic/billing/datalayer/BillRepository.java, billing-service/src/main/java/com/petclinic/billing/datalayer/DataSetupService.java, billing-service/src/main/java/com/petclinic/billing/presentationlayer/BillResource.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java, billing-service/src/test/java/com/petclinic/billing/datalayer/BillServicePersistenceTests.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceIntegrationTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceUnitTest.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/business/DataSetupService.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/data/OwnerRepo.java
=> merge from main to branch

api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/VetDTO.java, api-gateway/src/main/resources/static/scripts/vet-form/vet-form.controller.js, api-gateway/src/main/resources/static/scripts/vet-list/vet-list.controller.js, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/Vet.java, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/VetRepository.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/VetDTO.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/VetServiceImpl.java, vet-service/src/test/java/com/petclinic/vet/dataaccesslayer/VetRepositoryTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/VetServiceImplTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-692
This was to properly implement the update method in the UI because it was not showing all the fields properly. 
- Changed the controller.js for the form to display defaults for each value
- Had to change the downstream for naming conventions due to booleans being changed automatically in Spring Boot
=> feat(VVS-CPC-639): Implement vets update method in UI

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/BillServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillService.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillServiceImpl.java, billing-service/src/main/java/com/petclinic/billing/datalayer/BillRepository.java, billing-service/src/main/java/com/petclinic/billing/presentationlayer/BillResource.java
[JIRA: link to jira ticket
](https://champlainsaintlambert.atlassian.net/browse/CPC-702)
Adding the deleteBillsByCustomerId method to delete all bills by a specific customer. The UI and tests will soon be implemented.
=> feat/BILL CPC-702 Added the delete method for deleteBillsByCustomerId

api-gateway/src/main/resources/static/scripts/bundle-list/bundle-list.controller.js
Fixed issue with bundle list controller, since the list wouldnt show
removed arr variable in controller
=> Fix: removed array anotation in controller

billing-service/src/main/java/com/petclinic/billing/businesslayer/BillService.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillServiceImpl.java, billing-service/src/main/java/com/petclinic/billing/presentationlayer/BillResource.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceIntegrationTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceUnitTest.java
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15?modal=detail&selectedIssue=CPC-701&quickFilter=27)
This ticket is the added update methods for Bill service.
Added basic update methods to bill service. The tests were added with the service as well which they all pass.
Unit test for update does not function (despite my best efforts of course)
=>  feat/BILL-CPC-701-implement-update-methods

.github/workflows/go.yml, mailer-service/Dockerfile
=> Added swaggo version in dockerfile & Go workflow

api-gateway/src/main/resources/static/index.html
=> fix/Fix Angular version

api-gateway/Dockerfile, auth-service/Dockerfile, billing-service/Dockerfile, customers-service-reactive/Dockerfile, customers-service/Dockerfile, docker-compose.yml, inventory-service/Dockerfile, vet-service/Dockerfile, vets-service/Dockerfile, visits-service-new/Dockerfile, visits-service/Dockerfile
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-708
- modified Docker file's to java version 8 or 17 depending on what was there before. Removed the "-alpine" version and commented out the commands because the commands were invalid for the version. 
- Modified docker-compose to add the platform to emulate amd64 for everyone.
No changes to the UI
- mySql1 - mySql3 - mySql4 now emulate amd64
=> conf(INVT-CPC-708):cross_platform_conversion_for_development

api-gateway/lombok.config, api-gateway/src/main/java/com/petclinic/bffapigateway/config/GlobalExceptionHandler.java, api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/RatingResponseDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/ExistingVetNotFoundException.java, api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/InvalidInputException.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.controller.js, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, vet-service/src/lombok.config, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/Rating.java, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/RatingRepository.java, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/Specialty.java, vet-service/src/main/java/com/petclinic/vet/exceptions/ExistingVetNotFoundException.java, vet-service/src/main/java/com/petclinic/vet/exceptions/GlobalControllerExceptionHandler.java, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/DataSetupService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/RatingRequestDTO.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/RatingResponseDTO.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/RatingService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/RatingServiceImpl.java, vet-service/src/main/java/com/petclinic/vet/util/EntityDtoUtil.java, vet-service/src/test/java/com/petclinic/vet/dataaccesslayer/RatingRepositoryTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java
Set up the ratings table in vet's database and complete the get all ratings by vet id.
CPC-761
https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/13?modal=detail&selectedIssue=CPC-761&sprint=293
This ticket contains the set up of the rating's table, service, and repository which will be needed for the completion of the other CRUD operations (add rating, update rating, and delete rating). The get all ratings of a specific vet has also been implemented. We implemented this change to get a better view of the user's satisfaction of the vets. 
- The database setup service was updated to contain ratings for vets.
- The Rating Repository has been implemented (only the "findAllByVetId" method)
- The Rating Service and Service Impl have been …
=> feat(VETS-CPC-761): Set up the ratings table in vet's database and complete the get all ratings by vet id

README.md
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-795)
Updating the ReadMe to include the requirements needed for a user story to be considered as done.
Added the requirements definition for a user story to be considered done.
Before:
After:
=> doc(VIST-CPC-795): updated readme with the requirements needed for a user story to be considered done

api-gateway/src/main/java/com/petclinic/bffapigateway/utils/Security/Filters/JwtTokenFilter.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-832?atlOrigin=eyJpIjoiMTA1MTY4YTM1ZWRmNDdkMDk5YTg3MjI3Nzg2MDc2ZTMiLCJwIjoiaiJ9 
I fixed the chrome issue
Changed to accept headers based on simply html;
=> Bug/AUTH - Chrome compatibility issue 

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/BillServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Bills/BillDetails.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Bills/BillRequestDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Bills/BillResponseDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/bill-details/bill-details.template.html, api-gateway/src/main/resources/static/scripts/bill-history/bill-history.controller.js, api-gateway/src/main/resources/static/scripts/bills-by-owner-id/bills-by-owner-id.controller.js, api-gateway/src/main/resources/static/scripts/bills-by-vet-id/bills-by-vet-id.controller.js, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/BillServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillService.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillServiceImpl.java, billing-service/src/main/java/com/petclinic/billing/presentationlayer/BillResource.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceUnitTest.java
https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/35?modal=detail&selectedIssue=CPC-826&sprint=290
Worked on updating the DTO's as well as making changes and creating tests. Slight changes to UI
- Changed all code that uses BillDTO to use BillRequestDTO and BillResponseDTO (except the update method as Minseok will implement that for his story)
- Split BillDetails (in API-GATEWAY) to BillRequestDTO and BillResponseDTO and implemented this throughout the code
- Changed all tests that use BillDTO to use BillRequestDTO and BillResponseDTO 
- Created BillDomainClientIntegrationTest in API-Gateway and implemented tests
- Updated Bill detail page to include link to get all bills by a vet Id
- Updated the frontend to implement reactive flux …
=> bug(BILL-CPC-826): Integrated BillRequest DTO and BillResponseDTO into code

api-gateway/build.gradle, api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitDetails.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitRequestDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitResponseDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/visit-list/visit-list.template.html, api-gateway/src/main/resources/static/scripts/visits/visits.controller.js, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitService.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/DataSetupService.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/Visit.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/VisitRepo.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitController.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitRequestDTO.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitResponseDTO.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/DataLayer/VisitRepoTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitControllerUnitTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitsControllerIntegrationTest.java
https://champlainsaintlambert.atlassian.net/browse/CPC-764
This pull request is to switch the date value types in the visits-service to type LocalDateTime. LocalDateTime is a more precise and suitable data type for date and time information and is a step towards maintaining better consistency throughout the code base.
-Value type for Visit Dates has been changed to LocalDateTime from type Int
-All logic pertaining to findVisitByPractionerIdAndMonth has been disabled as it stands 
UI Before change
UI After change
=> feat(VIST-764): Change value type of visitDate from Int to LocalDateTime

api-gateway/src/main/resources/static/scripts/visit-list/visit-list.template.html, api-gateway/src/main/resources/static/scripts/visits/visits.js, docker-compose.yml
JIRA: https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/35?selectedIssue=CPC-762
Context:
I added a create visit button which when clicked will display a form for adding a new visit including a calendar
Changes
- Added a "Create Visit" Button
- Added CSS to the button and the H3 "Upcoming Visits" on the visit-list page
- Added routing to the "visitsNew" when the button is clicked
- I also temporarily changed the url for the create visit page since there is still work to be done for the old URL to make it work
Before the Change there was no "Create Visit" button and there was no way to access the create new visit page:
This is how the UI looks for the visit-list page
This is the create new visit page that the button navigates the user to
=> feat/(VIST-CPC-762) User can now navigate to create new visit page

README.md
JIRA: link to jira ticketdoc
After receiving many questions from contributors regarding the strange red and yellow errors on a git push after rebasing their branch, I deicded to highlight the passage in the README that explains what this "error" means. 
- Highlighed the need for git push -f after a rebase and/or merge conflic resolution.
- Added a screenshot of the "error" given when you don't use the -f option.
=> feat(none): Updated README.md

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/datalayer/Product/ProductRepository.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java, inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/datalayer/Inventory/InventoryRepositoryTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/datalayer/Product/ProductRepositoryTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/CPC-751 
I finished the backend for deleting all inventory and deleting all products by inventory
- added the delete method for deleting all inventory and deleting all products by inventory
- Doing the same thing for the api gateway
- Finish 4 types of testing for both methods
- Finish the api-gateway testing for delete all inventory and delete products inventory
=> Feat/invt CPC-751 inventory delete all

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/datalayer/Product/ProductRepository.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java, inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/datalayer/Product/ProductRepositoryTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/CPC-734
This pull request is about the backend implementation of the Update Product In Inventory feature of the inventory Service.
- Fully working backend methods UpdateProductInInventory
- ControllerUnitTest
- ControllerIntegrationTest
- ProductRepositoryIntegrationTest
- ServiceUnitTest
=> feat(INVT-CPC-734): Update product inside of inventory

README.md
The Readme file was updated to contain the requirement of 90% Jacoco coverage in the definition of done.
CPC-860
https://champlainsaintlambert.atlassian.net/browse/CPC-860
The Readme file was missing one important requirement which is having 90% Jacoco coverage on any new implementations that require testing.
- The line "Implementations that require testing need 90% of Jacoco coverage." was added to the README file
No changes to the UI were made.
=> doc(VETS-CPC-860):Update_Readme_File

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java
Finished implementing tests for the implementation of the post product to inventory
- Added tests in the inventory service and api gateway 
- modified the save product to use save method instead of insert
- updated status code on the post to return correct status codes
No changes to the ui since it was just testing 
- https://github.com/cgerard321/champlain_petclinic/pull/400
- https://github.com/cgerard321/champlain_petclinic/compare/feat/INVT-CPC-730_Ability_To_Add_Product_To_An_Inventory_ProjectStructureAndServiceLogicSetup?expand=1
- https://github.com/cgerard321/champlain_petclinic/pull/372
=> Feat/(INVT-CPC-730): ability to add a product to an inventory pt2

api-gateway/src/main/resources/static/index.html, api-gateway/src/main/resources/static/scripts/inventory-list/inventory-service.js, api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.controller.js, api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.template.html, api-gateway/src/main/resources/static/scripts/product-form/product-form.controller.js, api-gateway/src/main/resources/static/scripts/product-form/product-form.js, api-gateway/src/main/resources/static/scripts/product-form/product-form.template.html
Took 1 hour 59 minutes
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-730
Fixing bug for the post product to inventory, it now works and redirects you back to the product inventory list.
- Changed the logic and added a service method to keep track of the inventory id
- https://github.com/cgerard321/champlain_petclinic/pull/372
- https://github.com/cgerard321/champlain_petclinic/compare/feat/INVT-CPC-730_Ability_To_Add_Product_To_An_Inventory_ProjectStructureAndServiceLogicSetup?expand=1
- https://github.com/cgerard321/champlain_petclinic/pull/400
- https://github.com/cgerard321/champlain_petclinic/pull/447
=> (INVT-CPC-730): ability to add  product in inventory pt3

api-gateway/src/main/resources/static/scripts/Inventory-form/inventory-form.controller.js, api-gateway/src/main/resources/static/scripts/Inventory-form/inventory-form.js, api-gateway/src/main/resources/static/scripts/inventory-list/inventory-list.template.html, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/CPC-758
I added the update inventory feature to modify an inventory.
- I added the button for update inventory and it is fully functional 
- I finished all the methods for update and fixed all thier testing
=> feat(INVT_CPC-758): update_inventoryById

api-gateway/src/main/resources/static/scripts/bill-details/bill-details.template.html, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillService.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillServiceImpl.java, billing-service/src/main/java/com/petclinic/billing/presentationlayer/BillResource.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceIntegrationTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/CPC-750?atlOrigin=eyJpIjoiZmJlNDE1MDdlYzBkNDk2NzhjNmQ2YWZmZGE2ZDY2ZGYiLCJwIjoiaiJ9
Implemented the getBillById request on a full-stack level.
Naming conventions, best practices, and UI change for this request. DTO has been split into Request and Response.
Before:
After:
=> feat(BILL-CPC-750): Implement UI for getBillById

api-gateway/src/main/resources/static/scripts/vet-details/vet-details.template.html
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-939?atlOrigin=eyJpIjoiOGQ4YmQyZWY0YzM3NGI4MDhiZGI5MzI5NGExNzJhNzciLCJwIjoiaiJ9
Move the ratings table to its own location and adjusted the code for the look of the percentages list. 
I moved the ratings table into its own row, underneath the percentages, and added rating features. Additionally, I surrounded the list of the percentages in a container and modified the margins to better center the list while remaining responsive to the page.
=> bug(VETS-CPC-939): Fixed the ratings table and fixed the percentages table

api-gateway/src/main/java/com/petclinic/bffapigateway/config/GlobalExceptionHandler.java, api-gateway/src/main/java/com/petclinic/bffapigateway/config/GlobalServletExceptionHandler.java, api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Auth/UserDetails.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Auth/UserPasswordLessDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/app.js, api-gateway/src/main/resources/static/scripts/auth/admin-panel/admin-panel.controller.js, api-gateway/src/main/resources/static/scripts/auth/admin-panel/admin-panel.template.html, api-gateway/src/main/resources/static/scripts/auth/login-form/login-form.controller.js, api-gateway/src/main/resources/static/scripts/fragments/nav.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, auth-service/build.gradle, auth-service/src/main/java/com/auth/authservice/Util/AdminAccount/DatabaseLoaderService.java, auth-service/src/main/java/com/auth/authservice/Util/Configuration/Security/PasswordValidation.java, auth-service/src/main/java/com/auth/authservice/Util/GlobalControllerExceptionHandlerConfig.java, auth-service/src/main/java/com/auth/authservice/businesslayer/UserService.java, auth-service/src/main/java/com/auth/authservice/businesslayer/UserServiceImpl.java, auth-service/src/main/java/com/auth/authservice/datalayer/roles/Role.java, auth-service/src/main/java/com/auth/authservice/datalayer/roles/RoleRepo.java, auth-service/src/main/java/com/auth/authservice/datalayer/user/User.java, auth-service/src/main/java/com/auth/authservice/datalayer/user/UserIdentifier.java, auth-service/src/main/java/com/auth/authservice/datamapperlayer/UserMapper.java, auth-service/src/main/java/com/auth/authservice/presentationlayer/User/UserController.java, auth-service/src/main/java/com/auth/authservice/presentationlayer/User/UserDetails.java, auth-service/src/main/java/com/auth/authservice/security/JwtTokenUtil.java, auth-service/src/main/resources/schema-mysql.sql, auth-service/src/test/java/com/auth/authservice/businesslayer/AuthServiceUserServiceTests.java, auth-service/src/test/java/com/auth/authservice/presentationlayer/User/UserControllerIntegrationTest.java
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-889?atlOrigin=eyJpIjoiYzkwODA1MTZiZGQ3NDViOWJiNjdmODgzMTA4YWM1MjgiLCJwIjoiaiJ9)
This ticket was about implementing the get all users and adding UUID to the user. I took the time to test and achieve 90% coverage in the AUTH-service.
-UUID implemented
-Get all implemented
-Admin dashboard is only visible to admin role
-90% coverage in AUTH-service
=> feat(AUTH-CPC-889): auth implement get all users for the admin dashboard

api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.controller.js, api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.template.html
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-898
Needed to fix when no field is search it get all product
- Fix Search when no field are enter
- Reform search function front end
=> INVT_CPC-898_fix_product_search_refresh_list

api-gateway/src/main/resources/static/scripts/owner-form/owner-form.template.html, api-gateway/src/main/resources/static/scripts/owner-register/owner-register.template.html
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-900?atlOrigin=eyJpIjoiMTUxZTEyYTZiMzI2NDAyZThkZDA2YzAyN2Y3YWQ0MDciLCJwIjoiaiJ9
This story was simply to make the field requisites stricter for Owners. Before, we could input as big as big of a first name as we wished, for example. This may impose a security or reliability risk, so after consulting with the POs, We concurred at 50 characters for the limit. We could also input emojis which will just cause issues in a real life project. Foreign characters aren't accepted anymore since only ASCII characters are accepted. If a user submits a form with unacceptable fields, it will warn the user via a dialogue box that they must respect the ASCII formatting rule.
ADDED 50 character maximum to all form fields for Register and Edit Owner …
=> feat(CSTM-CPC-900) Error Handling for Owners

api-gateway/src/main/java/com/petclinic/bffapigateway/config/GlobalExceptionHandler.java, api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/InvalidInputsInventoryException.java, api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/InventoryNotFoundException.java, api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/ProductListNotFoundException.java, api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.controller.js, api-gateway/src/main/resources/static/scripts/product-form/product-form.controller.js, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/utils/DataBaseLoaderService.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java
https://champlainsaintlambert.atlassian.net/browse/CPC-872
This pull request implements exception handling for the inventory-service while squashing bugs
- Implemented exceptions for inventory-service in the domain client layer
- These additions affects all inventory methods in the domain client
- Relevant error codes will be shown instead of regular 500
=> bug(INVT-CPC-872): implement exceptions in domain_client

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java, inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/CPC-953
What is the ticket about and why are we doing this change?
- I implemented the get-all inventory method 
- I tested all possible methods
- it affects inventory management 
- it affects the delete inventory by id
- it affects the update inventory by id
=> Feat(INVT-CPC-953):Ability to get inventory by id 

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/resources/static/index.html, api-gateway/src/main/resources/static/scripts/Inventory-form/inventory-form.controller.js, api-gateway/src/main/resources/static/scripts/Inventory-form/inventory-form.js, api-gateway/src/main/resources/static/scripts/app.js, api-gateway/src/main/resources/static/scripts/inventory-list/inventory-list.template.html, api-gateway/src/main/resources/static/scripts/inventory-list/inventory-service.js, api-gateway/src/main/resources/static/scripts/inventory-update-form/inventory-update-form.component.js, api-gateway/src/main/resources/static/scripts/inventory-update-form/inventory-update-form.controller.js, api-gateway/src/main/resources/static/scripts/inventory-update-form/inventory-update-form.js, api-gateway/src/main/resources/static/scripts/inventory-update-form/update-form.template.html
https://champlainsaintlambert.atlassian.net/browse/CPC-896
Created a new form called inventory-update-form ,
Added functionality for a user to update a specific inventory
the form gets the Id of a specific inventory and displays the values in the form
##Changes
I separated the update inventory form logic, from the inventory form by creating another folder called inventory-update
My changes affect inventory management.
Before, when a user clicked on the edit form they would get a form that would say add new inventory and the form wouldn't be prefilled with values.
Now, a user is directed to a form that says update form and the form is already filled with prefilled values from that inventory.
Before:
After
=> Feat(INVT-CPC 896 ): fix update inventory visual bug

visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitsControllerIntegrationTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-965
Exception Handling was done for every attribute of the request that is made when posting. However, we have changed Status from a boolean to an enum class. So changes had to be made concerning that.
Added another else if in my validateRequestDTO method inside our service in order to check if the Status is REQUESTED.
=> feat(VIST-CPC-965): Implement Exception Handling For Status

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Inventory/InventoryRequestDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Inventory/InventoryResponseDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Inventory/InventoryTypeRequestDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Inventory/InventoryTypeResponseDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/Inventory-form/inventory-form.controller.js, api-gateway/src/main/resources/static/scripts/Inventory-form/inventory-form.template.html, api-gateway/src/main/resources/static/scripts/inventory-update-form/inventory-update-form.controller.js, api-gateway/src/main/resources/static/scripts/inventory-update-form/update-form.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/datalayer/Inventory/Inventory.java, inventory-service/src/main/java/com/petclinic/inventoryservice/datalayer/Inventory/InventoryType.java, inventory-service/src/main/java/com/petclinic/inventoryservice/datalayer/Inventory/InventoryTypeRepository.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryRequestDTO.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryResponseDTO.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryTypeRequestDTO.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryTypeResponseDTO.java, inventory-service/src/main/java/com/petclinic/inventoryservice/utils/DataBaseLoaderService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/utils/EntityDTOUtil.java, inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/datalayer/Inventory/InventoryRepositoryTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-894
When you want to search for an inventory type if the inventory type is not found it create the new type
- Modify inventory type from an enum to a repository
- Added post method
- Change front end dropdown
- Added search bar
=> feat(INVT CPC-894): Ability to add and search inventory type

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/datalayer/Product/ProductRepository.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java
https://champlainsaintlambert.atlassian.net/browse/CPC-885
- I implemented the get product by id method in the Inventory Service
- Added the get product by Id in both the inventory service client and api gateway controller.
- My changes affect managing products.
-  This change affects the update product by product id.
- Without my change, one of my partners cannot finish their story which is update the product.
=> feat(INVT-CPC-885):Ability to get product by product Id

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.controller.js, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/education/EducationService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/education/EducationServiceImpl.java, vet-service/src/main/java/com/petclinic/vet/util/EntityDtoUtil.java, vet-service/src/test/java/com/petclinic/vet/dataaccesslayer/EducationRepositoryTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/EducationServiceImplTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-936?atlOrigin=eyJpIjoiNDc0OGRkZjYzZTNmNDY5NmIwYjRlNjU2OTFlMDg3MTAiLCJwIjoiaiJ9
Added the ability to add an education to a vet
Added the post method for education. I created an interactive front end that allows the user to input the details of an education and add it to the vet and I implemented testing.
=> feat(VETS-CPC-936):Add educations to a vet

docker-compose.yml, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/DataSetupService.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DomainClientLayer/VetsClient.java
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-970)
The hardcoded vetId for our visits in our data loader was bad. We have updated it to the hardcoded vetId given in the Vet-Service in their dataloader.
Simply changed the values of vetId in our data loader when creating a visit.
**BEFORE**
**AFTER**
=> feat(VIST-CPC-969): Changing vet id to valid vet

api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Vets/VetDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Vets/Workday.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.template.html, api-gateway/src/main/resources/static/scripts/vet-form/vet-form.controller.js, api-gateway/src/main/resources/static/scripts/vet-form/vet-form.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, billing-service/src/main/java/com/petclinic/billing/datalayer/VetDTO.java, billing-service/src/main/java/com/petclinic/billing/datalayer/Workday.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/Vet.java, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/Workday.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/DataSetupService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/VetDTO.java, vet-service/src/test/java/com/petclinic/vet/dataaccesslayer/VetRepositoryTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/EducationServiceImplTest.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/RatingServiceImplTest.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/VetServiceImplTest.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DomainClientLayer/VetDTO.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DomainClientLayer/Workday.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitControllerUnitTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitsControllerIntegrationTest.java
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-904)
Modified the workday field and modified the front end to be checkboxes when selecting the workdays
- modified all vetdtos to switch workdays from a string to an enum
- created the workday enum
- modified the details page to show a list of the workdays of a vet
- modified the form page to have checkboxes instead of an input box when modifying or adding a vet
=> feat(VETS-CPC-904): change workdays of a vet to an enum

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/inventory-list/inventory-list.controller.js, api-gateway/src/main/resources/static/scripts/inventory-list/inventory-list.template.html, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java, inventory-service/src/main/java/com/petclinic/inventoryservice/utils/DataBaseLoaderService.java, inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-863
Added pagination for the inventory list
-Added pagination
-Added data for the inventory list
-Modify query params with search so that pagination works even when we search in the inventory
Before
After
=> Feat(INVT CPC-863): Pagination for inventory list

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java
[## Context:](https://champlainsaintlambert.atlassian.net/browse/CPC-899)
What is the ticket about and why are we doing this change
-Added integration controller testing for regex and paging logic.
-Fixed a bug where it would only show the letter and not the entirety of the searched name. So now if i can do letter, number or name.
What are the various changes and what other modules do those changes affect?
- Covers 100% of the method that i updated so jacoco shows better test results
=> Feat/invt cpc 889 Add Test And Fixed Search Issues

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/CustomersServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/owner-list/owner-list.controller.js, api-gateway/src/main/resources/static/scripts/owner-list/owner-list.js, api-gateway/src/main/resources/static/scripts/owner-list/owner-list.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/CustomerServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/business/OwnerService.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/business/OwnerServiceImpl.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/presentationlayer/OwnerController.java, customers-service-reactive/src/test/java/com/petclinic/customersservice/business/OwnerServiceImplTest.java, customers-service-reactive/src/test/java/com/petclinic/customersservice/presentationlayer/OwnerControllerIntegrationTest.java
JIRA: https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/14?selectedIssue=CPC-858&sprints=305
this ticket is about adding/implementing filters while at the same time using pagination
- Relocated the filters to the top of the table instead of placing them inside.
- Introduced three new endpoints:
1- getTotalNumberOfOwners
2- getTotalNumberOfOwnersWithFilters
3- getOwnersByPagination
- Ensured that the entire page is responsive, adapting to various screen sizes.
- Established a connection between the frontend and backend, enabling owners to be filtered while also providing pagination.
- Implemented a comprehensive set of tests to achieve good code coverage and to cover a wide range of filter combinations.
- Included a pagination navigation bar at the bottom for …
=> feat(CSTM-CPC-858): Add filtering functionalities for current owners page

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/CustomersServiceClient.java, api-gateway/src/main/resources/static/index.html, api-gateway/src/main/resources/static/scripts/app.js, api-gateway/src/main/resources/static/scripts/owner-details/owner-details.controller.js, api-gateway/src/main/resources/static/scripts/owner-details/owner-details.template.html, api-gateway/src/main/resources/static/scripts/pet-details/pet-details.component.js, api-gateway/src/main/resources/static/scripts/pet-details/pet-details.controller.js, api-gateway/src/main/resources/static/scripts/pet-details/pet-details.js, api-gateway/src/main/resources/static/scripts/pet-details/pet-details.template.html, customers-service-reactive/src/main/java/com/petclinic/customersservice/business/DataSetupService.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-999?atlOrigin=eyJpIjoiMGM4NjA1MmEwMmM4NDI0MGJlZGIwMmIyYmE0ZTg5OTMiLCJwIjoiaiJ9
The owner detail page doesn't look like the end product. Moving more info to a specific pet details page cleans up excessive info
Clicking a pets name in the owner details page opens a specific pet details page with all it's information
New Page:
Need to move edit, delete and active status buttons here
=> feat(CSTM-CPC-999) Add Pet Details page

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/index.html, api-gateway/src/main/resources/static/scripts/app.js, api-gateway/src/main/resources/static/scripts/auth/admin-panel/admin-panel.controller.js, api-gateway/src/main/resources/static/scripts/auth/admin-panel/admin-panel.template.html, api-gateway/src/main/resources/static/scripts/auth/signup/signup-form.template.html, api-gateway/src/main/resources/static/scripts/auth/user-details/user-details.components.js, api-gateway/src/main/resources/static/scripts/auth/user-details/user-details.controller.js, api-gateway/src/main/resources/static/scripts/auth/user-details/user-details.js, api-gateway/src/main/resources/static/scripts/auth/user-details/user-details.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, auth-service/src/main/java/com/petclinic/authservice/businesslayer/UserService.java, auth-service/src/main/java/com/petclinic/authservice/businesslayer/UserServiceImpl.java, auth-service/src/main/java/com/petclinic/authservice/datalayer/user/UserRepo.java, auth-service/src/main/java/com/petclinic/authservice/presentationlayer/User/UserController.java, auth-service/src/main/resources/schema-mysql.sql, auth-service/src/test/java/com/petclinic/authservice/businesslayer/AuthServiceUserServiceTests.java, auth-service/src/test/java/com/petclinic/authservice/presentationlayer/User/UserControllerIntegrationTest.java
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-890?atlOrigin=eyJpIjoiN2EyMmMxYzQ1MzE4NDY4M2JjMzM3M2MyNjhmM2ZhNTEiLCJwIjoiaiJ9)
As an administrator, I need the capability to view detailed information about specific users within the system. This feature is essential for effective user management and account retrieval.
1. Implemented with the get-all in the admin.
2. UUID of the specific user should be visible
2. Should have a filter to find by username.
3. Does not require an exact name match for the username (partial matches are acceptable).
4. Test coverage for related methods of over 90%
5. Recentered the spinner on the signup page
Center the spinner
#Before
#After
- Some changes Will be made regarding the UI of this pull request in future PRs
=> feat(AUTH-CPC-890): implement get by id and by username for users

api-gateway/src/main/resources/static/scripts/visits/visits.controller.js, api-gateway/src/main/resources/static/scripts/visits/visits.template.html
link to JIRA ticket:
https://champlainsaintlambert.atlassian.net/browse/CPC-1001
This ticket is related to a simple UI change by adding a back button to the NewVisit form to switch the view back to the visitList page more easily.
- Added a goBack() scope to the visits controller
- Added a 'Back' button in the visit-template.html
- Before Changes (without button):
- After Changes (button added)
- Back to Visit-List page
=> feat(VIST-CPC-1001): back button added to newVisit form

api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitRequestDTO.java, api-gateway/src/main/resources/static/scripts/visits/visits.controller.js, api-gateway/src/main/resources/static/scripts/visits/visits.template.html, docker-compose.yml
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-946)
This ticket serves the purpose of allowing the user to choose an owner and than a pet of the owner chosen to be added to the new visit. 
The reason why we added it was because the previous post URL contained no pet or owner id so when a visit was added the pet Id column was empty for a new visit. This ticket fixed that and now display the pet Id related to the visit
- The first change was adding 2 new drop downs to the form which contain the owners and the pets of that owners
- The drop downs are filled dynamically based on a function that sends a get request to retrieve all the owners and the pets
- Once a successful visit is made, the form automatically routes the user back to the visit list page to …
=> feat(VIST-CPC-946) add option to choose owner and pet for visit

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/inventory-list/inventory-list.controller.js, api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.controller.js, api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.js, api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/datalayer/Product/ProductRepository.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java, inventory-service/src/main/java/com/petclinic/inventoryservice/utils/DataBaseLoaderService.java, inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-873
Added pagination to products in the inventory
- Added new endpoints to complete pagination
- added methods to modularize requests
- added buttons in the UI
=> feat: (INVT-CPC-873) add pagination functionality to inventory product list

docker-compose.yml
Took 7 minutes
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-877
Closing the ports on the servuces
- Closed ports in AUTH and Customer service
- Requests to the service now needs to be done within curl locally in the docker container.
- No changes to the UI
- If you don't know how to write your curl commands with the payload write the request in postman and it will generate the appropriate Curl command with the payload
=> conf(INVT-CPC-877): Closed the opened ports to the services in the docker-compose

README.md
updated README with information about SSH Keys
Added SSH Key Infroamtion
- Added steps to keep passphrase to avoid entering passphrase at each command that requires permission
=> doc(INVT-CPC-1007): update read me to include ssh keys

docker-compose.yml
Took 3 minutes
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1009
Fixed the bug with the lists when you try and bring the service up or build.
- Removed the commented out ports and removed the ports section.
=> bug(INVT-CPC-1009):Fixed the list issue in the docker-compose

api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.controller.js, api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.template.html, api-gateway/src/main/resources/static/scripts/product-form/product-form.template.html
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-983
Have a consistent format with dollar signs and decimal points for money.
- Added dollar sign
- Added formatting for decimal point
- Fix adding new product so it is possible to have a decimal point
Before
After
=> Feat(INVT CPC-983): Ability to represent factual data in a consistent format

api-gateway/src/main/resources/static/scripts/inventory-list/inventory-list.controller.js, api-gateway/src/main/resources/static/scripts/inventory-list/inventory-list.template.html, api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.controller.js, api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.template.html
https://champlainsaintlambert.atlassian.net/browse/CPC-985
-Ability to restore inventory or products within few second range
- Modified the controller in the front end for both inventory and product
- Added a restore button that if you click it will cancel the delete feature
- Added a custom notification for when it's successfully deleted
For Inventory
After clicking on delete :
After clicking restore:
For Products
After clicking on delete :
After clicking restore:
=> Feat(INVT-CPC-985): Ability_Restore_Deleted_Inventory_And_Product

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
https://champlainsaintlambert.atlassian.net/browse/CPC-1002
This ticket is about giving  authorizations to certain roles for Inventory, where the roles were not specified.
- Added roles for endpoints that had no roles or user permisions
- My changes affect Inventory and Vets
=> Feat(INVT-CPC-1002 ):Ability to set the proper roles to the end points

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/auth/admin-panel/admin-panel.controller.js, api-gateway/src/main/resources/static/scripts/auth/admin-panel/admin-panel.template.html, api-gateway/src/main/resources/static/scripts/auth/user-details/user-details.controller.js, api-gateway/src/main/resources/static/scripts/auth/user-details/user-details.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, auth-service/src/main/java/com/petclinic/authservice/businesslayer/UserService.java, auth-service/src/main/java/com/petclinic/authservice/businesslayer/UserServiceImpl.java, auth-service/src/main/java/com/petclinic/authservice/presentationlayer/User/UserController.java, auth-service/src/test/java/com/petclinic/authservice/businesslayer/AuthServiceUserServiceTests.java, auth-service/src/test/java/com/petclinic/authservice/presentationlayer/User/UserControllerIntegrationTest.java
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-915?atlOrigin=eyJpIjoiY2IzZTQ3ZWRmOTE5NGZlY2EyMjRjZmZhMTNhZDg2ZTQiLCJwIjoiaiJ9)
This ticket is about deleting a user. As an admin, you want to be able to freely delete users from your system at your convenience. 
1. Admin must be logged in
2. Must have a valid UUID
3. The user must exist 
4. Fix display on the user details page
5. Rework the query search for get by username
#Before
#After
- Included the changes promised in the previous PR
=> feat(AUTH-CPC-915): implement delete user in the admin panel

billing-service/src/main/java/com/petclinic/billing/datalayer/DataSetupService.java
JIRA: https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15/backlog?selectedIssue=CPC-1016
This ticket is about fixing (updating) the due dates, so that the due dates accurately reflect the real-time status.
- DateSetupService in billing-service
=> bug (BILL-CPC-1016): Fix Due Dates for Bills

api-gateway/src/main/resources/static/scripts/bill-history/bill-history.template.html
https://champlainsaintlambert.atlassian.net/browse/CPC-1008
The search filters were outside of the table and not as comprehensive. Removed the old search bars & vet and owner ID. Added more search filters and placed them inside the table for a more visually appealing interface.
-bill-history.template.html
Before:
After:
=> Feat/BILL CPC-1008 Search bill history table columns

.github/workflows/qodana_code_quality.yml
JIRA: No ticket will be made.
Temporary disabling the Qodana scan until Qodana licensing issues are fixed with @cgerard321
=> Temporary disabling of Qodana until licensing issues can be fixed

.github/workflows/go.yml, mailer-service/Dockerfile, mailer-service/mailer/controller/mailer.controller_test.go
=> Get random port for mailer tests

api-gateway/build.gradle, docker-compose.yml
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1102)
The angular front end at localhost:8080 was not displaying anything. The Network log revealed that certain resources were not found.
- api-gateway build.gradle updated to add missing dependencies (that seemed to have been lost in a previous merge)
- updated docker-compose.yml to add some empty lines after the products-service was added
After bug fix:
=> bug(CPC-1102): fix angular frontend

api-gateway/build.gradle, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/OwnerController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/OwnerControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigAuthService.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigCustomersService.java, petclinic-frontend/src/features/customers/api/updateOwner.ts, petclinic-frontend/src/features/customers/models/OwnerRequestModel.ts, petclinic-frontend/src/features/customers/models/OwnerResponseModel.ts, petclinic-frontend/src/features/customers/models/PetResponseModel.ts, petclinic-frontend/src/pages/Customer/ProfileEdit.css, petclinic-frontend/src/pages/Customer/ProfileEdit.tsx, petclinic-frontend/src/router.tsx, petclinic-frontend/src/shared/models/path.routes.ts
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1077
Created a v2 endpoint to update an owner's information and web page where the logged in customer can update their information.
- Created the OwnerController class in the v2 folder of the API gateway
- Created the endpoint to update an owner's information in the Controller
- Created two controller integration tests to cover the implementation of the endpoint
- Added the mockserver depency in build.gradle
- Created the ProfileEdit page where customers can update their information on a pre-filled form. The pre-filled information is based on the logged in customer.
- Created the necessary files for the implementation of the ProfileEdit page (models, API calls, CSS)
=> feat/(CUST-CPC-1077): Update customer information on website

inventory-service/src/main/java/com/petclinic/inventoryservice/utils/DataBaseLoaderService.java, petclinic-frontend/src/features/inventories/InventoriesListTable.tsx, petclinic-frontend/src/features/inventories/InventoryProducts.tsx
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1045 
Fixed the front-end of supply inventories to be more user friendly. Also fixed filter searches, where they wouldn't be working when either combined, or would only work when pressing the "search" button, which also isn't user-friendly
- Removed the inventoryId from the visual front-end
- Changed products inside of the inventories to be referred to as supplies
- Added more inventories, inventoryTypes, and supplies to the database
Before: 
After:
- Removed commented out data (used by previous years)
- https://github.com/cgerard321/champlain_petclinic/pull/631
=> Fixed different filter searches, and removed inventoryId from the visual

inventory-service/src/main/java/com/petclinic/inventoryservice/datalayer/Product/Status.java, inventory-service/src/main/java/com/petclinic/inventoryservice/utils/EntityDTOUtil.java, petclinic-frontend/src/features/inventories/InventoryProducts.tsx, petclinic-frontend/src/features/inventories/models/ProductModels/ProductModel.ts, petclinic-frontend/src/features/products/ProductsList.tsx, petclinic-frontend/src/features/products/api/getAllProducts.ts
**JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1131
Fixed the front-end of status to show the result based on the quantity of supplies. Also, fixed the logic for status and now the result is displaying instead of null.
No
- Add the Status section inside the products information
- The status changes when the quantity is 0 that is equals to OUT_OF_STOCK, when the quantity is lest than 20 the status is equal to RE_ORDER and finally when the quantity is bigger than 20 the status is available.
- Fix the logic for status 
Before:
After:
https://github.com/cgerard321/champlain_petclinic/pull/647
=> Implemented front-end for status in supplies

petclinic-frontend/src/features/inventories/InventoryProducts.css, petclinic-frontend/src/features/inventories/InventoryProducts.tsx
**JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1062
The ticket is about to be able to see a specific color of the status based on their availability. We are doing this change to facilitate the visual and also it is another way to inform the user to perform a specific task based on the status.
No
-The status changes color based on the quantity. 
-The status became red when the quantity is 0, yellow when the quantity less than 20 and green when the quantity is more than 20.
Before
After
=> Implemented the color green/yellow/red based on the status type

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryController.java, package-lock.json, package.json, petclinic-frontend/.eslintrc.json, petclinic-frontend/.prettierrc.json, petclinic-frontend/README.md, petclinic-frontend/index.html, petclinic-frontend/package-lock.json, petclinic-frontend/package.json, petclinic-frontend/src/features/customers/components/UpdateCustomerForm.css, petclinic-frontend/src/features/inventories/EditInventory.tsx, petclinic-frontend/src/features/inventories/InventoriesListTable.css, petclinic-frontend/src/features/inventories/InventoriesListTable.tsx, petclinic-frontend/src/features/inventories/InventoryProducts.css, petclinic-frontend/src/features/inventories/models/InventoryModels/InventoryRequestModel.ts, petclinic-frontend/src/features/inventories/models/InventoryModels/InventoryResponseModel.ts, petclinic-frontend/src/features/products/ProductList.css, petclinic-frontend/src/features/visits/Review/AddForm.css, petclinic-frontend/src/features/visits/Review/EditForm.css, petclinic-frontend/src/features/visits/VisitListTable.css, petclinic-frontend/src/layouts/AppNavBar.css, petclinic-frontend/src/pages/Customer/AddingCustomer.css, petclinic-frontend/src/pages/Customer/AllOwners.css, petclinic-frontend/src/pages/Error/ErrorPage.css, petclinic-frontend/src/router.tsx, petclinic-frontend/src/shared/api/EditInventory.ts, petclinic-frontend/src/shared/models/path.routes.ts, petclinic-frontend/tsconfig.json, petclinic-frontend/tsconfig.node.json, petclinic-frontend/vite.config.ts
[**JIRA:** link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1052)
This push is for the front end and back end of the edit inventory button
No
- The edit button looks a little different with colors and text
- When you click the button, it redirects you to a new page
- The new page has a form pre-populated with the information on the inventory 
- You can edit the form and save
Please accept my Pull Request
=> feat(INVT-CPC-1052): Fix Edit Inventory

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/OwnerController.java, petclinic-frontend/src/layouts/AppNavBar.css, petclinic-frontend/src/layouts/AppNavBar.tsx, petclinic-frontend/src/pages/Customer/AddingCustomer.tsx, petclinic-frontend/src/pages/Customer/AllOwners.tsx
https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15/backlog?selectedIssue=CPC-1061&text=CUST
As a Customer, I need to be able to get the information of customers/pet owners by id. The information includes the owner’s information, pets and bills.
- Affected front end
- AllOwners.tsx page + css
- Navbar and navbar css
- Back end: Added v2 endpoint for customer get by id
=> Moved everything from my previous branch to this one

petclinic-frontend/src/pages/Customer/AddingCustomer.tsx, petclinic-frontend/src/pages/Customer/AllOwners.css, petclinic-frontend/src/pages/Customer/AllOwners.tsx
https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15/backlog?selectedIssue=CPC-1063&text=CUST
As a Customer, I want to be able to see my pets.
- Added pets table in front end AllCustomers.tsx
- Added functions for calculating age and know pet type
- Fixed css import for AddingCustomer.tsx
- Made tables be able to be larger
=> Added pets when searching by id in the AllOwners.tsx page.

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VetController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/VetControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigVetService.java, petclinic-frontend/package-lock.json, petclinic-frontend/src/features/inventories/AddInventoryType.css, petclinic-frontend/src/features/inventories/InventoriesListTable.css, petclinic-frontend/src/features/products/components/StarRating.css, petclinic-frontend/src/features/veterinarians/VetListTable.tsx, petclinic-frontend/src/layouts/AppNavBar.css, petclinic-frontend/src/pages/Vet/Vet.tsx, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java
Any user can now get all vets and view their information in a table.
- implemented getall in api gateway
- tested getall in api gateway
- implemented the frontend for getall in a table format
BEFORE:
AFTER:
=> feat(VETS-CPC-1071): get all vets

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java
This ticket is about fixing the angular frontend, as the get all, average rating, and number of ratings were not being fetched.
- removed the hard coded values in the method uri
- added "/vets" to the vetsServiceUrl
Before:
After:
=> feat(VETS-CPC-1157_Fix_Angular_Frontend): fixed angular frontend

petclinic-frontend/src/features/visits/Review/Api/getVisitByVisitId.ts, petclinic-frontend/src/features/visits/VisitListTable.tsx, petclinic-frontend/src/features/visits/visits/VisitByVisitId.tsx, petclinic-frontend/src/features/visits/visits/VisitDetails.css, petclinic-frontend/src/pages/Visit/VisitByVisitid.tsx, petclinic-frontend/src/router.tsx, petclinic-frontend/src/shared/models/path.routes.ts
https://champlainsaintlambert.atlassian.net/browse/CPC-1126
adding a front-end page for the getVisitByVisitId, so the user can see all the details of one of his visit more clearly.
- Modified the front end to show the detail of one visit on one page
If this is a change to the UI, include before and after screenshots to show the …
=> VIST-CPC-1126: Implement GetVisitByVisitId On The FrontEnd

petclinic-frontend/src/features/inventories/InventoryProducts.css, petclinic-frontend/src/features/inventories/InventoryProducts.tsx
**JIRA:https://champlainsaintlambert.atlassian.net/browse/CPC-1062
Fixed bug with colors for status supplies, New pull request broke the feature
I just took out the link with css and implemented the colors directly inside the <td>
https://github.com/cgerard321/champlain_petclinic/pull/647
https://github.com/cgerard321/champlain_petclinic/pull/657
https://github.com/cgerard321/champlain_petclinic/pull/647
=> feat(INVT-1062): Fix bug for status colors

package-lock.json, package.json, petclinic-frontend/src/features/inventories/InventoriesListTable.tsx, petclinic-frontend/src/layouts/AppNavBar.css, petclinic-frontend/src/pages/Customer/AllOwners.css, petclinic-frontend/src/pages/Home/Home.css, petclinic-frontend/src/pages/User/Login.css
[**JIRA:** link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1163)
This is a feature to delete multiple inventory items at once because before you had either the option to delete the entire inventory or one by one.
No
Only the InventoriesListTable.tsx is changed
Please accept my pull request
=> feat(INVT-CPC-1163): Delete Selected Inventories

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/OwnerController.java, package-lock.json, package.json, petclinic-frontend/src/layouts/AppNavBar.tsx, petclinic-frontend/src/pages/Customer/ProfilePage.css, petclinic-frontend/src/pages/Customer/ProfilePage.tsx, petclinic-frontend/src/router.tsx, petclinic-frontend/src/shared/models/path.routes.ts
[**JIRA:** link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1169)
Added a profile Page where Owners can go look at their information and add a button to the update page if they would like to update
No
- Created ProfilePage.tsx.
- Created ProfilePage.css.
- Created a page where profile can view their infromation.
- Created a button that can bring them to the edit profile.
=> feat/(CUST-CPC-1169): Customer Profile Page

api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Products/ProductRequestDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/ProductController.java, petclinic-frontend/src/features/products/ProductsList.tsx, petclinic-frontend/src/features/products/api/addProduct.ts, petclinic-frontend/src/features/products/components/AddProduct.tsx, petclinic-frontend/src/layouts/AppNavBar.tsx, products-service/src/main/java/com/petclinic/products/businesslayer/products/ProductServiceImpl.java, products-service/src/main/java/com/petclinic/products/presentationlayer/products/ProductRequestModel.java, products-service/src/main/java/com/petclinic/products/utils/EntityModelUtil.java, products-service/src/main/java/com/petclinic/products/utils/GlobalControllerExceptionHandler.java, products-service/src/main/java/com/petclinic/products/utils/exceptions/InvalidAmountException.java, products-service/src/main/resources/application.yml, products-service/src/test/java/com/petclinic/products/datalayer/ratings/RatingRepositoryIntegrationTest.java, products-service/src/test/java/com/petclinic/products/presentationlayer/products/ProductControllerIntegrationTest.java
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1122)
This ticket is to give to the inventory manager the ability to POST new products.
Nope😉
- Added tests to the products-service
- modified the version of Flapdoodle from 5.0.5 to 4.4.0, because the tests weren't working well
- Modified the requestModels to accpect a averageRating
- Added a new TypeScript file to make the POST request
- Added a new React TypeScript file for the button and modal
- Modified the Product component to show the button
**Before**
**After**
Pull request 
https://github.com/cgerard321/champlain_petclinic/pull/618
=> feat(PROD-CPC-1122): add products

inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/test/java/com/petclinic/inventoryservice/utils/EntityDTOUtilTest.java
**JIRA:https://champlainsaintlambert.atlassian.net/browse/CPC-1062
Test the code for EntityDTOUtil
-Add Tests for the EntityDTOUtil
=> Implemented test for EntityDTOUtil

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/BillController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/BillControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/BillControllerUnitTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigBillService.java, package-lock.json, package.json, petclinic-frontend/src/features/bills/AdminBillsListTable.tsx, petclinic-frontend/src/features/bills/api/getAllBills.tsx, petclinic-frontend/src/layouts/AppNavBar.tsx, petclinic-frontend/src/pages/Bills/AdminBill.tsx, petclinic-frontend/src/router.tsx, petclinic-frontend/src/shared/models/path.routes.ts
Added admin authorization to the bills page. When admin is logged in, the admin can view all the bills in the database.
No
- Added getAllBills function to the BillController in the api-gateway.
- Created the page for admins to view all existing bills.
- Authorization to only allow admins to view all customer's pages
=> feat(BILL-CPC-1059): display all customer bills for the admin 

cart-service/src/main/java/com/petclinic/cartsservice/businesslayer/CartService.java, cart-service/src/main/java/com/petclinic/cartsservice/businesslayer/CartServiceImpl.java, cart-service/src/main/java/com/petclinic/cartsservice/presentationlayer/CartController.java, cart-service/src/test/java/com/petclinic/cartsservice/businesslayer/CartServiceUnitTest.java, cart-service/src/test/java/com/petclinic/cartsservice/presentationlayer/CartControllerUnitTest.java
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1160)
This change adds a new feature to return the number of items in a user's cart via the GET /api/v1/carts/{cartId}/count endpoint. This allows users to easily track how many products they have added to their cart.
This does not make any changes to the .vscode folder.
Added a new GET /api/v1/carts/{cartId}/count endpoint in the CartController.
Implemented the service logic in CartService to return the number of products in the cart.
Added error handling for cases where a cart is not found (returns 404).
Wrote unit tests to ensure the item count functionality works as expected and error cases are covered.
The productIds list is counted, but the cart itself remains intact.
Unit tests are included to …
=> feat(CART-CPC-1160): Add cart item count feature and tests

api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Vets/SpecialtyDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VetController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/VetControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigVetService.java, petclinic-frontend/src/features/veterinarians/VetListTable.css, petclinic-frontend/src/features/veterinarians/VetListTable.tsx, petclinic-frontend/src/features/visits/visits/VisitByVisitId.tsx, petclinic-frontend/src/pages/Vet/VetDetails.css, petclinic-frontend/src/pages/Vet/VetDetails.tsx, petclinic-frontend/src/router.tsx, petclinic-frontend/src/shared/models/path.routes.ts, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/VetServiceImpl.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1074
Context:
By clicking on the veterinarian's name in the "Veterinarians" tab, it brings you to the veterinarian details page.
Changes
Created the VetDetails page which can be accessed by valid vetId and gives information about the veterinarian.
Created my method inside the VetController in the v2 folder inside the api-gateway.
Created tests for the "VetControllerIntegrationTest" inside the api-gateway.
Fixed tests inside the vet-service.
BEFORE: it was a blank page, and you couldn't access the VetDetails page with Id
AFTER:
=> Feat/vets cpc 1074 get vet by vet Id

auth-service/src/main/java/com/petclinic/authservice/businesslayer/UserServiceImpl.java, auth-service/src/main/java/com/petclinic/authservice/domainclientlayer/cart/CartRequest.java, auth-service/src/main/java/com/petclinic/authservice/domainclientlayer/cart/CartResponse.java, auth-service/src/main/java/com/petclinic/authservice/domainclientlayer/cart/CartService.java, auth-service/src/main/java/com/petclinic/authservice/domainclientlayer/cart/CartServiceImpl.java, auth-service/src/main/resources/application.yml, auth-service/src/test/java/com/petclinic/authservice/presentationlayer/User/UserControllerIntegrationTest.java, cart-service/src/main/java/com/petclinic/cartsservice/businesslayer/CartService.java, cart-service/src/main/java/com/petclinic/cartsservice/businesslayer/CartServiceImpl.java, cart-service/src/main/java/com/petclinic/cartsservice/presentationlayer/CartController.java, cart-service/src/main/resources/application.yaml, cart-service/src/test/java/com/petclinic/cartsservice/businesslayer/CartServiceUnitTest.java, cart-service/src/test/java/com/petclinic/cartsservice/dataaccesslayer/CartRepositoryUnitTest.java, cart-service/src/test/java/com/petclinic/cartsservice/presentationlayer/CartControllerUnitTest.java
[JIRA: link to jira
https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/73/backlog?selectedIssue=CPC-1057 ##
Context:
Added a new feature to create a cart for each new user upon registration
Does this PR change the .vscode folder in petclinic-frontend?:
This does not make any changes to the .vscode folder.
Changes:
-Implemented the creation of a new empty cart upon user registration
-Added a client to call the Cart service, automatically creating an empty cart for each new user registration
Dev notes (Optional)
=> feat/(CART-CPC-1057): Add Cart To Each New User 

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java
This ticket is about adding exception handling for client exceptions and specifying the other exception handlings since it was not being done before. Api gateway testing has also been updated accordingly.
- added client exception handling for every method in the VetsServiceClient class
- specified the error for the server exception handling for every method in the VetsServiceClient class
- updated api gateway accordingly
=> bug(VETS-CPC-1141_Make_Service_Client_Handle_Exceptions): made exception handling for client

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/CartServiceClient.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/CartServiceClientTest.java
https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/73/backlog?selectedIssue=CPC-1057
Adding call to the endpoint to create new cart
does not change anything
adding new method in cartClientService and create Cart integration test
=> feat/(CART-CPC-1057): Add Cart To Each New User in Gateway

petclinic-frontend/src/features/carts/components/CartItem.tsx, petclinic-frontend/src/features/carts/components/CartTable.css, petclinic-frontend/src/features/carts/components/CartTable.tsx, petclinic-frontend/src/features/carts/components/UserCart.tsx, petclinic-frontend/src/features/carts/models/ProductModel.ts, petclinic-frontend/src/features/visits/visits/VisitByVisitId.tsx, petclinic-frontend/src/router.tsx
**JIRA:** https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15/backlog?selectedIssue=CPC-1033
The butto View cart in the list table now redirect to the cart itself with all of its products 
no it does not
- modified the UserCart file so it displays correctly all the products
- modified the CartList so the button View Cart works
- Created a fetch to get the cart by id
=> feat/CART-CPC-1033_View cart button displaying a user's cart

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/ProductsServiceClient.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/ProductsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/ProductControllerUnitTest.java, products-service/src/main/java/com/petclinic/products/utils/DataLoaderService.java, products-service/src/test/java/com/petclinic/products/presentationlayer/products/ProductControllerIntegrationTest.java
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1086)
Needed to create all the classes in the products-service and setup the api-gateway to handle requests related to that service
Nop😉
Added new tests. There are no UI changes.
[Pull request link](https://github.com/cgerard321/champlain_petclinic/pull/618)
=> conf(PROD-CPC-1086): configuring products service and api gateway part 2

api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/CartServiceClientTest.java, cart-service/src/main/java/com/petclinic/cartsservice/businesslayer/CartServiceImpl.java, cart-service/src/main/java/com/petclinic/cartsservice/presentationlayer/CartController.java, cart-service/src/test/java/com/petclinic/cartsservice/businesslayer/CartServiceUnitTest.java, cart-service/src/test/java/com/petclinic/cartsservice/presentationlayer/CartControllerUnitTest.java
**JIRA:** https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15/backlog?selectedIssue=CPC-1044
Adding tests for get all in the cart service and API gateway
No.
- Tests for get all added to service unit test and controller tests.
- Tests added to api gateway
=> Feat/(CART-CPC-1044) Testing in API gateway and for get all methods

Diagrams/basic-token-validation.puml, api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClient.java
**JIRA:** N/A
Bug with the logout, where the cookie was not being deleted
N/A
- Made sure to delete token whatever the status of the cookies
- Fixed the path and the way the cookie is being sent back
=> bug(AUTH): Small fix for logout

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryControllerTest.java, petclinic-frontend/src/features/inventories/AddInventoryForm.css, petclinic-frontend/src/features/inventories/AddInventoryForm.tsx, petclinic-frontend/src/features/inventories/AddInventoryType.css, petclinic-frontend/src/features/inventories/AddInventoryType.tsx, petclinic-frontend/src/features/inventories/InventoriesListTable.tsx, petclinic-frontend/src/features/inventories/api/addInventory.ts
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1155
Added the functionality to add an inventory
- Added a addInventory API to fetch information from the backend
- Added a addInventoryForm to show a form when clicking on the addInventoryButton, allowing the user to input information regarding the inventory they want to add.
- Added methods to add an Inventory for the backend
- Implemented two tests to test the methods added in the backend for the API-Gateway
Before: The addInventory would do nothing.
After:
- There is no ability to edit an inventory that was already added, seems like the fetching or another error in the front end is causing this issue.
- Adding an inventory type will allow a user to select it when adding an inventory from the menu
None
=> feat(INVT-1155) Add Inventory

petclinic-frontend/src/features/inventories/InventoryProducts.tsx
**JIRA:https://champlainsaintlambert.atlassian.net/browse/CPC-1152
-Implement a delete button for deleting supplies inside an inventory
-Added a delete button inside InventoryProducts.tsx
-When the delete button is pressed, the supply is deleted in the database as well
Before
After
-Only changed the front end since the back end and all test are already done
=> Implemented a delete button for delete a supply

petclinic-frontend/src/features/veterinarians/VetListTable.tsx
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1248?atlOrigin=eyJpIjoiYmRmMDM1NmMyNjE4NGY1ZmE0OGJlMDQxZWQ5NzA2OWYiLCJwIjoiaiJ9
This ticket is about deleting a veterinarian by their ID, the admin needs to have this ability to ensure that the list of vets is up-to-date, especially when a vet can quit or be fired. 
So this change fixes a problem where the vet was not properly deleted from the database. Also, it fixes a bug where after clicking the "delete" button, it was navigating the admin to the vet's detail page instead of staying on the list.
No, this PR does not modify the .vscode folder
- Fixed the delete functionality so that it properly deletes the veterinarian record from database (MongoDB).
- Addressed a bug …
=> bug(VETS-CPC-1248): Fix delete vet by vet ID

petclinic-frontend/src/pages/Vet/UpdateVet.tsx
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1277)
My handleSpecilitiesChanges wasn't good coding. So I changed it to have a cleaner and better code overall.
No it does not make any changes to the .vscode file.
- I just changed the handleSpecialitiesChange method to have better coding. 
Before:
After:
=> bug(VETS-CPC-1277): fix update vet

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/EmailSendingFailedException.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/UserController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/AuthControllerUnitTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/domainclientlayer/AuthServiceClientControllerIntegrationTest.java, auth-service/build.gradle, auth-service/src/main/java/com/petclinic/authservice/Util/Exceptions/EmailSendingException.java, auth-service/src/main/java/com/petclinic/authservice/Util/Exceptions/EmailSendingFailedException.java, auth-service/src/main/java/com/petclinic/authservice/Util/GlobalControllerExceptionHandlerConfig.java, auth-service/src/main/java/com/petclinic/authservice/businesslayer/UserService.java, auth-service/src/main/java/com/petclinic/authservice/businesslayer/UserServiceImpl.java, auth-service/src/main/java/com/petclinic/authservice/domainclientlayer/NewEmailingService/DirectEmailModelRequestDTO.java, auth-service/src/main/java/com/petclinic/authservice/domainclientlayer/NewEmailingService/EmailModelResponseDTO.java, auth-service/src/main/java/com/petclinic/authservice/domainclientlayer/NewEmailingService/EmailingServiceClient.java, auth-service/src/main/java/com/petclinic/authservice/security/JwtTokenUtil.java, auth-service/src/main/resources/application.yml, auth-service/src/test/java/com/petclinic/authservice/businesslayer/AuthServiceUserServiceTests.java, auth-service/src/test/java/com/petclinic/authservice/presentationlayer/User/UserControllerIntegrationTest.java, emailing-service/emailing-service/BuisnessLayer/EmailServiceImpl.cs, petclinic-frontend/src/layouts/AppNavBar.tsx, petclinic-frontend/src/pages/User/Login.tsx, petclinic-frontend/src/pages/User/SignUp.css, petclinic-frontend/src/pages/User/SignUp.tsx, petclinic-frontend/src/router.tsx, petclinic-frontend/src/shared/models/OwnerRequestModel.ts, petclinic-frontend/src/shared/models/RegisterModel.ts, petclinic-frontend/src/shared/models/UserIdLessRoleLessDTO.ts, petclinic-frontend/src/shared/models/path.routes.ts
[**JIRA:** link to jira ticket](https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15/backlog?selectedIssue=CPC-1188)
It doesn't do any changes to the vscode folder
- Added sign up page and relevant css
- Created V2 functions in the api gateway for createUser
- Created V2 functions in the api gateway for verifyUser
- Added EmailSendingFailedException
- Added 3 tests in new class v2/AuthControllerUnitTest
- Added 3 tests in new class v2/domainclientlayer/AuthServiceClientControllerIntegrationTest
- Added 1 test in new class …
=> Feat(CUST-CPC-1188): Users can register on the website using a sign up page

petclinic-frontend/src/pages/Customer/ProfilePage.css, petclinic-frontend/src/pages/Customer/ProfilePage.tsx
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1221
I made it possible for the customer to see the information (and list) of their pets
Nope
- Added a pet section in the ProfilePage.tsx
- Changed the CSS to include the Pet information and also to look a lot more like the the other pages we have created 
Before
After
=> feat/(CUST-CPC-1221): Display Pets On Customer Profile

petclinic-frontend/src/features/inventories/EditInventoryProducts.tsx, petclinic-frontend/src/features/inventories/InventoryProducts.tsx
[**JIRA:** link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1231)
This push is to add the back button which helps to navigate back to inventories once you are in products and also some changes in the edit inventory form
No
- Added back button
- UI changes for edit inventory form
Before
After
Please accept my Pull Request
=> feat(INVT-CPC-1231): Add Back Button

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VetController.java, petclinic-frontend/src/pages/Vet/VetDetails.tsx, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/Specialty.java, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/SpecialtyDTO.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/VetService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/VetServiceImpl.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java
**JIRA:** link to jira ticket https://champlainsaintlambert.atlassian.net/browse/CPC-1285
After my first assigned task (get vets by photo file name) proved to be a fool's errand, our team quickly created a new  fullstack story for me to be able to do, so i added a feature to add a specialty to a vet by their id
-changed the vets …
=> feat(VETS-CPC-1285): add specialties by vet

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/CustomersServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/PetController.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/business/PetService.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/business/PetServiceImpl.java, customers-service-reactive/src/main/java/com/petclinic/customersservice/presentationlayer/PetController.java, petclinic-frontend/src/features/customers/api/deletePet.ts, petclinic-frontend/src/features/customers/api/updatePet.ts, petclinic-frontend/src/features/customers/components/CustomerDetails.tsx, petclinic-frontend/src/features/customers/components/UpdatePetForm.css, petclinic-frontend/src/features/customers/components/UpdatePetForm.tsx, petclinic-frontend/src/pages/Customer/AllOwners.css, petclinic-frontend/src/pages/Customer/AllOwners.tsx
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1228
Allows an admin and a vet do delete an owner's pet.
No...
- Created a v2 endpoint for pet deletion.
- Only Admins and Vets can delete a pet.
- Created a v2 deletepet service method since the old one returned nothing, but I want it to return a PetResponseModel so I can use the data after the delete request.
- Improved UI of AllOwners page.
- Added the delete button in the edit pet page
- Changed pet type to be a drop down menu.
- Made the update and delete buttons user-friendly by displaying a pop up to either display a success message or a confirmation.
Before:
After:
The tests will be added in another PR, one of my teammate needs this part for their story.
=> feat(CUST-CPC1229): admin or vet can delete customer pet

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/CartServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Cart/AddProductRequestDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Cart/CartProductResponseDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Cart/CartRequestDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Cart/CartResponseDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Cart/UpdateProductQuantityRequestDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/CartController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/CartServiceClientTest.java, cart-service/src/main/java/com/petclinic/cartsservice/businesslayer/CartService.java, cart-service/src/main/java/com/petclinic/cartsservice/businesslayer/CartServiceImpl.java, cart-service/src/main/java/com/petclinic/cartsservice/dataaccesslayer/cartproduct/CartProduct.java, cart-service/src/main/java/com/petclinic/cartsservice/domainclientlayer/AddProductRequestModel.java, cart-service/src/main/java/com/petclinic/cartsservice/domainclientlayer/ProductClient.java, cart-service/src/main/java/com/petclinic/cartsservice/domainclientlayer/ProductResponseModel.java, cart-service/src/main/java/com/petclinic/cartsservice/domainclientlayer/UpdateProductQuantityRequestModel.java, cart-service/src/main/java/com/petclinic/cartsservice/presentationlayer/CartController.java, cart-service/src/main/java/com/petclinic/cartsservice/presentationlayer/CartResponseModel.java, cart-service/src/main/java/com/petclinic/cartsservice/utils/DataLoaderService.java, cart-service/src/main/java/com/petclinic/cartsservice/utils/exceptions/OutOfStockException.java, cart-service/src/test/java/com/petclinic/cartsservice/businesslayer/CartServiceUnitTest.java, cart-service/src/test/java/com/petclinic/cartsservice/presentationlayer/CartControllerUnitTest.java, petclinic-frontend/src/features/carts/components/CartItem.css, petclinic-frontend/src/features/carts/components/CartItem.tsx, petclinic-frontend/src/features/carts/components/UserCart.tsx, petclinic-frontend/src/features/carts/models/ProductModel.ts
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1257)
This ticket implements a feature for the Cart module where users are notified if they attempt to add more items to their cart than are available in stock. Additionally, the feature will show a low stock notification next to items in the cart when fewer than 5 items are left.
No, this PR does not change the .vscode folder in petclinic-frontend.
Changes:
This PR introduces the following changes to the Cart module:
Backend Changes:
Added API Methods:
Implemented addProductToCart and updateProductQuantityInCart methods in the Cart service.
These methods validate stock availability before adding or updating products in the cart.
Custom Exceptions:
Introduced OutOfStockException to handle scenarios …
=> feat(CART-CPC-1257): implement stock check and notifications

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/CartServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/CartController.java, cart-service/src/main/java/com/petclinic/cartsservice/businesslayer/CartService.java, cart-service/src/main/java/com/petclinic/cartsservice/businesslayer/CartServiceImpl.java, cart-service/src/main/java/com/petclinic/cartsservice/presentationlayer/CartController.java
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1273)
When you go in carts and then view carts, you can see cart products. This ticket implements the feature to remove a product in cart.
- Addition of removeProductFromCart method
- Implementation of the said method
- Implements tests
- Changed UserCart.tsx for it to be able to handle the deletion of an item present in cart
BEFORE:
AFTER:
=> feat(CART-CPC-1273): Remove product from cart

api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/PetControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigCustomersService.java, customers-service-reactive/src/test/java/com/petclinic/customersservice/business/PetServiceUnitTest.java, customers-service-reactive/src/test/java/com/petclinic/customersservice/presentationlayer/PetControllerUnitTest.java
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1228
Added all the tests to cover the implementations made in the previous PR.
It doesn't
- Created 2 tests in PetServiceUnitTest
- Created 1 test in PetControllerUnitTest
- Created 4 tests in PetControllerIntegrationTest
https://github.com/cgerard321/champlain_petclinic/pull/837
=> feat(CUST-CPC-1228): tests for vet or admin can delete customer pet

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryControllerTest.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java, inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java, petclinic-frontend/src/features/carts/components/CartItem.css, petclinic-frontend/src/features/carts/components/UserCart.css, petclinic-frontend/src/features/customers/components/AddPetForm.css, petclinic-frontend/src/features/customers/components/CustomerDetails.css, petclinic-frontend/src/features/inventories/CardInventoryTeam.module.css, petclinic-frontend/src/features/inventories/InventoriesListTable.module.css, petclinic-frontend/src/features/inventories/InventoryProducts.tsx, petclinic-frontend/src/features/products/ProductList.css, petclinic-frontend/src/features/products/api/ProductDetails.css, petclinic-frontend/src/features/products/components/EditProduct.css, petclinic-frontend/src/features/products/components/Image.css, petclinic-frontend/src/features/visits/Emergency.css, petclinic-frontend/src/features/visits/Emergency/AddEmergencyForm.css, petclinic-frontend/src/pages/Inventory/Inventories.css, petclinic-frontend/src/pages/Vet/VetDetails.css
**JIRA:** link to jira ticket https://champlainsaintlambert.atlassian.net/browse/CPC-1237?atlOrigin=eyJpIjoiZDExZmZkODg4Njk1NDVkY2FjYWQ0N2E1OTJkMjBiNzkiLCJwIjoiaiJ9 
Allowing a vet or an admin to remove deduct 1 from a product's quantity once inside of an inventory's product list through a button.
No.
Allowing a vet or an admin to remove deduct 1 from a product's quantity once inside of an inventory's product list through a button.
The button should be disabled if the quantity of product is 0.
The state of availability should refresh based on the new quantity.
Before:
After:
=> feat(INVT-CPC-1237): consume inventory product

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VetController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/VetControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigVetService.java, petclinic-frontend/src/features/veterinarians/api/deleteVetPhoto.ts, petclinic-frontend/src/pages/Vet/DeleteVetPhoto.tsx, petclinic-frontend/src/pages/Vet/VetDetails.css, petclinic-frontend/src/pages/Vet/VetDetails.tsx, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/PhotoService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/PhotoServiceImpl.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/VetServiceImpl.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/PhotoServiceImplTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1253
This ticket implements the functionality to allow to admin to delete a veterinarian's profile photo from the vet details page and revert it to the default profile image without reloading the page.
This PR doesn't make any changes to the .vscode nor deletes it.
Frontend Changes:
- Implemented a React component DeleteVetPhoto.tsx that provides a "Delete Photo" button below the vet's profile picture.
- The handle requires the admin's confirmation before deleting it.
- deleteVetPhoto.ts contains the API call to the backend to delete photo in the frontend.
- Moved fetchVetPhoto …
=> feat(VETS-CPC-1253): delete profile photo

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VetController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/VetControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/VetControllerUnitTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigVetService.java, petclinic-frontend/src/features/veterinarians/api/addVet.ts, petclinic-frontend/src/features/veterinarians/api/deleteVetPhoto.ts, petclinic-frontend/src/features/veterinarians/models/VetRequestModel.ts, petclinic-frontend/src/features/veterinarians/models/VetResponseModel.ts, petclinic-frontend/src/pages/Vet/AddVet.tsx, petclinic-frontend/src/pages/Vet/DeleteVetPhoto.tsx, petclinic-frontend/src/pages/Vet/VetDetails.css, petclinic-frontend/src/pages/Vet/VetDetails.tsx, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/PhotoService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/PhotoServiceImpl.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/VetServiceImpl.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/PhotoServiceImplTest.java
https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/73/backlog?selectedIssue=CPC-1260&text=cart
Context:
This ticket is about the implementation of the promos , the admin cand add, remove , update and delete promos that the users will be able to use in their Cart.
Does this PR change the .vscode folder in petclinic-frontend?:
No
If the PR changes the .vscode folder, explain why in detail because it should not.
Reviewers need to check for any changes to the
.vscode folder and add a comment about it to their review comments.
Changes
=> feat(CART-CPC-1260): Add and manage Promo code

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryController.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1298
We are removing unecessary endpoints to increase our test coverage.
**No, it does not**
•**Removed** endpoints we no longer needeed
Nothing changed in the UI
=> task(INVT-CPC-1298): removed unecessary endpoints

petclinic-frontend/src/features/bills/BillsListTable.css, petclinic-frontend/src/features/bills/BillsListTable.tsx
**JIRA:** 
https://champlainsaintlambert.atlassian.net/browse/CPC-1199?atlOrigin=eyJpIjoiZDIyMmIyMGQ2MmYxNDQyMmIyN2E3YWE5OWQ5MjM3OTMiLCJwIjoiaiJ9
Made the UI uniform between admin and customers bills page.
No.
- Added CSS for the customers bills page
- Doesn't affect anything else
Before:
After:
=> bug(BILL-CPC-1199): Improved UI for customers bills page

products-service/src/main/java/com/petclinic/products/utils/EntityModelUtil.java
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1302)
When adding a product the productQuantity would always be set to null, so we needed to fix that bug.
Where's Jared?
I just added a line of code to map the productQuantity from the productRequestModel to the Product entity
There are no UI changes
=> bug(PROD-CPC-1302): productQuantity is Null

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryControllerTest.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java, inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java, petclinic-frontend/src/features/inventories/InventoryProducts.tsx, petclinic-frontend/src/features/inventories/api/deleteAllProductsFromInventory.ts
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1385
Implemented the ability for a vet to delete all of the supplies inside of a specific inventory
No, it does not
- Added controller methods in both the service and the API-Gateway
- Added the methods in the ProductInventory service and the ProductInventoryServiceImpl
- Added tests inside of the service and the api-gateway (100% coverage for both)
- Added a button to the front-end
- Added an api method that uses axios to use the back-end method.
Before:
After:
=> feat(INVT-CPC-1385) Delete all supplies from an inventory

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/BillController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/BillControllerUnitTest.java, petclinic-frontend/package-lock.json, petclinic-frontend/package.json, petclinic-frontend/src/features/bills/AdminBillsListTable.tsx, petclinic-frontend/src/features/bills/api/getAllOverdueBills.tsx, petclinic-frontend/src/features/bills/api/getAllPaidBills.tsx, petclinic-frontend/src/features/bills/api/getAllUnpaidBills.tsx
I implemented a drop down menu to filter the admin bills by their status, paid, unpaid or overdue.
It doesn't
- Created three new methods in the BillController in the api-gateway
- Created three new axios api calls 
- Modified the AdminBillsListTable to have the drop down manu and to diplay the proper bills
- Added three controller unit tests for the three new methods
Before:
After: …
=> feat(BILL-CPC-1240): Drop down menu to filter admin bills by status

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/ProductController.java
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1261)
The ticket addresses an issue where the rating functionality does not work properly. Specifically, when a user attempts to add a rating with any role other than an Administrator, a 403 error is thrown, but the rating is still saved. This PR is being made to resolve the issue so that the rating functionality works as expected for all roles, not just administrators.
- Fixed the issue causing a 403 error when adding a rating …
=> bug/(PROD-CPC-1261): Rating not working properly

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VetController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/VetControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigVetService.java, petclinic-frontend/src/pages/Vet/VetDetails.css, petclinic-frontend/src/pages/Vet/VetDetails.tsx, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/AlbumService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/AlbumServiceImpl.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/AlbumServiceImplTest.java
**JIRA:** link to jira ticket: https://champlainsaintlambert.atlassian.net/browse/CPC-1250
I finished my fullstack, delete a photo from the photo album of photos in the vets details page
-affected 11 files
-album service/service impl
-vets controller
- vets details and its css
- api gateway v2 controller for vets 
- controller and service tests for vets
- api gateway v2 testing …
=> feat(VETS-CPC-1382):delete album photo

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/BillController.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/ProductController.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VetController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/BillControllerUnitTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/VetControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigVetService.java, petclinic-frontend/package-lock.json, petclinic-frontend/package.json, petclinic-frontend/src/features/bills/AdminBillsListTable.tsx, petclinic-frontend/src/features/bills/api/getAllOverdueBills.tsx, petclinic-frontend/src/features/bills/api/getAllPaidBills.tsx, petclinic-frontend/src/features/bills/api/getAllUnpaidBills.tsx, petclinic-frontend/src/features/veterinarians/models/EducationRequestModel.ts, petclinic-frontend/src/features/veterinarians/models/EducationResponseModel.ts, petclinic-frontend/src/pages/Vet/VetDetails.css, petclinic-frontend/src/pages/Vet/VetDetails.tsx, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/AlbumService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/AlbumServiceImpl.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/AlbumServiceImplTest.java
https://champlainsaintlambert.atlassian.net/browse/CPC-1326
I'm doing these changes because having the low stock products displayed as text in the bottom of the page is poor UI. I decided to improve the UI by redirecting the user to another page where the low stock products will be displayed by inventory in tables.
No, it doesn't.
I improved the UI by displaying the low stock products on a seperate page instead of displaying them in text at the bottom of the page. I created a LowStockProdcuct.tsx page and made my button navigate to that page when it is clicked.
Before:
After:
=> feat(INVT-CPC-1326): Improve UI For Get All Low Stock Products

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java, petclinic-frontend/src/features/inventories/InventoriesListTable.tsx, petclinic-frontend/src/features/inventories/LowStockProducts.tsx, petclinic-frontend/src/router.tsx, petclinic-frontend/src/shared/models/path.routes.ts
https://champlainsaintlambert.atlassian.net/browse/CPC-1326
I'm doing these changes because having the low stock products displayed as text in the bottom of the page is poor UI. I decided to improve the UI by redirecting the user to another page where the low stock products will be displayed by inventory in tables.
No, it doesn't 
I improved the UI by displaying the low stock products on a seperate page instead of displaying them in text at the bottom of the page. I created a LowStockProdcuct.tsx page and made my button navigate to that page when it is clicked.
Before: 
After:
=> feat(INVT-CPC-1326): Improve UI For Get All Low Stock Products On Click

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryControllerTest.java, inventory-service/build.gradle, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java, inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java, petclinic-frontend/package-lock.json, petclinic-frontend/src/features/inventories/CreatePdfButton.tsx, petclinic-frontend/src/features/inventories/InventoryProducts.tsx, petclinic-frontend/src/features/inventories/api/createPdf.ts
**JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1324
-The vet can download in a pdf format all the supplies inside an specific inventory
-Implemented a new dependency for the pdf
-Implemented the logic 
-Implemented a button that download all supplies inside an inventory and put it inside a pdf
Before:
After :
=> feat(INVT-CPC-1324) Create Pdf for Supplies Inside an Inventory

petclinic-frontend/src/pages/Home/Home.css, petclinic-frontend/src/pages/Home/Home.tsx
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1387)
Users may now have a preview of three vets from our PetClinic team, who each have services they offer. They can also click on a vet they would like to know more about to see their details on the VetDetails page.
- Users now see a preview of three randomly selected vets from the PetClinic team.
- Each vet card shows the vet's name, services offered, and a photo.
- Clicking on a vet card navigates the user to the respective VetDetails page.
- Services offered by vets are randomly selected and displayed as bullet points.
- Home page UI has been updated in general.
Before:
After:
=> feat(VETS-CPC-1387): rework home page ui

petclinic-frontend/src/pages/Vet/VetDetails.tsx
**JIRA:** link to jira ticket: https://champlainsaintlambert.atlassian.net/browse/CPC-1405
i had overlooked a modal that opened when i deleted an image, it should be fixed by now
literally just one line in the vetDetails.tsx
If this is a new UI …
=> bug(VETS-CPC-1405) fix delete album photo button

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/ProductController.java
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1398)
Previously we weren't able to update the inventory as a inventory manager.
Nope😉
- Added the Inventory Manager role to the patch endpoint
None
=> bug(PROD-CPC-1398): update product quantity for Inventory Manager

emailing-service/emailing-service/BackgroundTask/RecurringJobService.cs
[**JIRA:** link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1358)
This tickets just make sure the emailing service launches all the time!
NO
Simply modified the recurring job service to handle the absence of a database
No UI
=> bug(VIST-CPC-1358): Fix emailing service not starting docker

petclinic-frontend/src/features/inventories/InventoryProducts.css, petclinic-frontend/src/features/inventories/InventoryProducts.tsx, petclinic-frontend/src/features/inventories/api/global.d.ts
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-888
As a vet, I would like to be able to translate an inventory in case I don't understand the current language of the inventory.
No, it does not
- Added a global.d.ts file to handle translations.
- Implemented methods inside the InventoryProducts.tsx file to be able to translate the inventory from the Google Translate translator from a dropdown menu.
Before:
After:
More languages can be used, but have to be added in the "includedLanguages". Currently, there are only 4 as they are the most popular/used languages.
=> feat(INVT-CPC-888): Added the ability to translate inventories.

petclinic-frontend/src/pages/Vet/VetDetails.tsx
https://champlainsaintlambert.atlassian.net/browse/CPC-1389
Work hours are now displayed in a clear calendar format instead of a confusing string representation.
No
- Implemented a calendar format for displaying work hours, improving clarity and usability.
- Merged consecutive hour ranges for a more concise representation.
Before:
After:
=> feat(VETS-CPC-1389): refactor workhours json

products-service/src/main/java/com/petclinic/products/businesslayer/products/ProductServiceImpl.java, products-service/src/main/java/com/petclinic/products/presentationlayer/products/ProductRequestModel.java, products-service/src/main/java/com/petclinic/products/utils/DataLoaderService.java, products-service/src/main/java/com/petclinic/products/utils/EntityModelUtil.java, products-service/src/test/java/com/petclinic/products/presentationlayer/products/ProductControllerIntegrationTest.java, products-service/src/test/java/com/petclinic/products/presentationlayer/products/ProductControllerUnitTest.java, products-service/src/test/java/com/petclinic/products/presentationlayer/ratings/RatingControllerIntegrationTest.java
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1411
Average rating seemed to be incorrectly implemented inside the DataLoader. This PR fixes this by adding Ratings in the DataLoader.
- Added Ratings to DataLoader
- Removed hardcoded averageRatings in the Product entity
- Reverted updateProduct method to commented out one
As the updateProduct has been reverted, please verify all edit methods work on your end. I have tested them and they work, but please do the due diligence to test if it didn't break anything.
=> bug(PROD-CPC-1411): average rating unexpected behavior fix

products-service/build.gradle
**JIRA:** none since this is configuration. Take a look at the slides
Increased the minimum jaccoco coverage to 90%
Nope😉
- Increased the minimum jaccoco coverage to 90%
None
=> conf(PROD): increased minimum Jacoco coverage

petclinic-frontend/src/features/inventories/AddSupplyToInventory.css, petclinic-frontend/src/features/inventories/AddSupplyToInventory.tsx, petclinic-frontend/src/features/inventories/InventoryProducts.tsx
**JIRA:https://champlainsaintlambert.atlassian.net/browse/CPC-1309
-Improve the front end for the form add supply
-Fixed the add button in the front end, because in a pr someone erase the button by accident 
- Improved the UI for the add supply
=> feat(INVT-CPC-1309): Improve form for add supply

petclinic-frontend/src/features/bills/AdminBillsListTable.tsx
https://champlainsaintlambert.atlassian.net/browse/CPC-1196
Implemented a search bar to filter all the bills by customer ID. Also added customer ID to the table to facilitate searches.
No it does not.
- Implemented a filter in the admin's table of bills.
- Installed the fontawesome plugin Adem mentioned.
Before: 
After:
=> feat(BILL-CPC-1196): filter all bills by customer id for admin

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryControllerTest.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java, inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java, petclinic-frontend/src/features/inventories/LowStockProducts.tsx, petclinic-frontend/src/features/inventories/models/InventoryModels/ProductRequestModel.ts, petclinic-frontend/src/features/inventories/models/InventoryModels/ProductResponseModel.ts
https://champlainsaintlambert.atlassian.net/browse/CPC-1355
I did this to improve my low stock supplies page by adding a button that will allow the user to restock the low stock supplies.
No, it doesn't.
The changes are:
- Added a button on my low stock supply page 
- The button displays a form that prompts the user to enter a quantity.
- The form includes display the total price that the restock will cost (multiplying the supply price by the quantity entered)
- After clicking on submit, the quantity of supplies is added to the supply quantity
This only affects the inventory module and nothing else.
Before:
After:
Linked Pull Request: 
https://github.com/cgerard321/champlain_petclinic/pull/920#issue-2577153473
=> feat(INVT-CPC-1355): Ability To Restock Low Stock Products

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Auth/RoleRequestModel.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/RoleController.java, api-gateway/src/main/java/com/petclinic/bffapigateway/utils/Security/Annotations/SecuredEndpoint.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/RoleControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigAuthService.java, auth-service/src/main/java/com/petclinic/authservice/businesslayer/RoleService.java, auth-service/src/main/java/com/petclinic/authservice/businesslayer/RoleServiceImpl.java, auth-service/src/main/java/com/petclinic/authservice/datalayer/roles/RoleRequestModel.java, auth-service/src/main/java/com/petclinic/authservice/presentationlayer/Role/RoleController.java, auth-service/src/test/java/com/petclinic/authservice/businesslayer/RoleServiceUnitTest.java, auth-service/src/test/java/com/petclinic/authservice/presentationlayer/User/RoleControllerIntegrationTest.java, petclinic-frontend/src/features/users/api/addRole.ts, petclinic-frontend/src/features/users/api/getAllRoles.ts, petclinic-frontend/src/features/users/model/RoleRequestModel.ts, petclinic-frontend/src/features/users/model/RoleResponseModel.ts, petclinic-frontend/src/layouts/AppNavBar.tsx, petclinic-frontend/src/pages/Users/AllRoles.css, petclinic-frontend/src/pages/Users/AllRoles.tsx, petclinic-frontend/src/router.tsx, petclinic-frontend/src/shared/models/path.routes.ts
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1359
Allow admin users to create roles
No
- Created RoleService, RoleServiceImpl, and RoleController
- Created v2 endpoints in RoleController
- Created tests for all implementations
- Created AllRoles page and modal form to create role
After:
=> feat(AUTH-CPC-1359): admin can create role

petclinic-frontend/src/features/inventories/InventoryProducts.tsx
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1416
There is a bug where if the supplies inside an inventory are set to 0 (empty), the inventory wouldn't render and not allow the user to do necessary requests.
- Removed the error message from the fetching inventories API call
- Added a message that says there are no supplies inside the current inventory.
Before:
After:
https://github.com/cgerard321/champlain_petclinic/pull/913 
& any other PR that used to be affected by not being able to access inventories when there were no supplies
=> bug(CPC-INVT-1416): Fix supply inventory page

inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java
**JIRA:https://champlainsaintlambert.atlassian.net/browse/CPC-1324
-Add test for inventory-service
-Add test for inventory-service
=> Test(INVT-CPC-1324): Create test pdf for supplies inside inventory

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/BillServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/BillController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/BillServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/BillControllerUnitTest.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillService.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillServiceImpl.java, billing-service/src/main/java/com/petclinic/billing/presentationlayer/BillController.java, billing-service/src/main/java/com/petclinic/billing/presentationlayer/CustomerBillsController.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillControllerIntegrationTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillControllerUnitTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/CustomerBillsControllerUnitTest.java
**JIRA:** 
https://champlainsaintlambert.atlassian.net/browse/CPC-926?atlOrigin=eyJpIjoiMDNiM2FkZWY1YTYzNDRiZjg0MTU5YzAxYjI3MDc4OGUiLCJwIjoiaiJ9
Changed the names of many methods in the backend to fit naming conventions.
No.
Many improperly named methods in the backend were changed to fit the naming conventions:
- getBilling -> getBillById
- getAllBilling -> getAllBills
- getAllPaidBilling -> getAllPaidBils
- getAllUnpaidBilling -> getAllUnpaidBills
- getAllOverdueBilling -> getAllOverdueBills
- getBillingInfo -> getBillById
- getAllBillingByPage -> getAllBillsByPage
- GetAllBillsByStatus -> getAllBillsByStatus
- GetAllBills -> getAllBills …
=> bug(BILL-CPC-926): Fix Naming

petclinic-frontend/src/features/inventories/InventoriesListTable.module.css, petclinic-frontend/src/features/inventories/InventoriesListTable.tsx, petclinic-frontend/src/pages/Inventory/Inventories.module.css
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1344
We are removing the buttons we had on the bottom of our inventory page and instead putting those buttons inside a menu which the users can click to see actions they can perform.
**No, it doesn't**
•Removed the buttons located in the bottom of our page
•Created a menu icon which can be clicked by the user to see actions that can be performed
**Before** this is how the bottom of our page looked like:
**After** this is how the bottom of our page looks like:
**After** this is the menu which users can click to see actions they can perform:
=> feat/(INVT-CPC-1344): improve mainpage user interface and experience

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/InventoryControllerTest.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/datalayer/Product/ProductRepository.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java, inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/datalayer/Product/ProductRepositoryTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java, petclinic-frontend/src/features/inventories/InventoriesListTable.module.css, petclinic-frontend/src/features/inventories/InventoryProducts.tsx, petclinic-frontend/src/features/inventories/LowStockProducts.tsx, petclinic-frontend/src/features/inventories/api/searchProducts.ts, petclinic-frontend/src/features/inventories/hooks/useSearchProducts.ts, petclinic-frontend/src/features/inventories/models/InventoryModels/ProductRequestModel.ts, petclinic-frontend/src/features/inventories/models/InventoryModels/ProductResponseModel.ts, petclinic-frontend/src/features/inventories/models/ProductModels/ProductModel.ts, petclinic-frontend/src/features/inventories/models/ProductModels/ProductModelINVT.ts, petclinic-frontend/src/features/inventories/models/ProductModels/Status.ts, petclinic-frontend/src/features/products/ProductList.css, petclinic-frontend/src/features/products/api/ProductDetails.css, petclinic-frontend/src/features/products/components/ProductSearch.tsx, petclinic-frontend/src/features/products/components/Sidebar.css, petclinic-frontend/src/features/promos/components/CardPromos.css, petclinic-frontend/src/pages/Inventory/Inventories.module.css, petclinic-frontend/src/pages/Product/Products.css
Before, the front-end was capable of filtering the status of the products of an inventory, but not the back-end. Now, the back-end method meant to search products inside of an inventory is supporting the filtering by name, description and status of products. This change was necessary for later development where the search product feature will be exploited outside of the current inventory products page.
No.
Back-end method meant to search products inside of an inventory is supporting the filtering by name, description and status of products.
Increase testing coverage in the inventory-service and the api-gateway …
=> feat(INVT-CPC-1153): Searching products status

petclinic-frontend/src/features/veterinarians/VetListCards.tsx, petclinic-frontend/src/features/veterinarians/VetListTable.tsx, petclinic-frontend/src/pages/Vet/UpdateVet.css, petclinic-frontend/src/pages/Vet/UpdateVet.tsx, petclinic-frontend/src/pages/Vet/VetDetails.tsx
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1391
This ticket is about  the "Update Profile" button. The button was inside the cards, which were inside the main page of the Vets (VetListTable).  I removed the "Update Profile" button from the home page and moved it to the VetDetails page , where the vet can update their profile.
No.
- Added a new CSS class for the form when you click the "Update Button".
- Removed the button from "VetListTable.tsx" and "VetListCards.tsx".
- Added the button to the "VetDetails.tsx" class.
- I added a call to the refreshVetDetails() function in the UpdateVet.tsx component. The refreshVetDetails() function is defined in VetDetails.tsx, and it's passed as a …
=> bug(VETS-CPC-1391): fix update button in vet details page 

petclinic-frontend/src/features/carts/components/UserCart.css, petclinic-frontend/src/features/carts/components/UserCart.tsx
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1396)
To add a button so that the user can be taken back to shopping more products.
- Added Continue Shopping Button
- Styled the Button with CSS
BEFORE: 
AFTER:
=> feat(CART-CPC-1396): Continue Shopping Button

petclinic-frontend/src/features/bills/AdminBillsListTable.css, petclinic-frontend/src/features/bills/AdminBillsListTable.tsx
**JIRA:** 
https://champlainsaintlambert.atlassian.net/browse/CPC-1312
Changed the design/ui of the bills page. Used to be very messy.
NO
Filter, search and create are now hidden and shown with a button and look nice and stylish.
Before:
After:
=> feat(BILL-CPC-1312): Updated UI for admin bills page

api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Auth/UserResponseDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/UserController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/UserControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigAuthService.java, petclinic-frontend/src/features/users/components/UserDetails.css, petclinic-frontend/src/features/users/components/UserDetails.tsx
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1337
Allow admins to add or remove user roles.
No
- Created v2 endpoint and test
- Added an update user roles button in UserDetails
- Created modal to update user roles
Before:
After:
=> feat(AUTH-CPC-1337): admin can update user roles

api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/AuthControllerUnitTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/domainclientlayer/AuthServiceClientControllerIntegrationTest.java
=> bug: Missing tests for api gateway

petclinic-frontend/.github/workflows/playwright.yml, petclinic-frontend/e2e/example.spec.ts, petclinic-frontend/tests-examples/demo-todo-app.spec.ts
added a folder for cart e2e testing
NO
no UI changes
=> Cart Page folder creation

petclinic-frontend/tests/ViewEmergencyById.spec.ts
--add a test for emergency by id
=> test for get emergency by id

petclinic-frontend/playwright.config.ts, petclinic-frontend/tests/tests-examples/demo-todo-app.spec.ts, petclinic-frontend/tests/tests-examples/e2e/test-1.spec.ts
Made an e2e test to add vet education and delete vet education  
No
Added e2e test files for adding and deleteing vet education
=> e2etest/VETS-Aian: E2E testing add vet education

petclinic-frontend/tests/inventoriespage/updateInventory.spec.ts
Added a test which checks that if an inventory is updated correctly, it should display a message saying "Inventory updated successfully".
=> Test for updating an inventory

petclinic-frontend/tests/inventoriespage/searchInventoryByName.spec.ts
Test in front-end for search by inventory name.
=> Test for search product by name

petclinic-frontend/tests/inventoriespage/deleteProductsInInventory.spec.ts
Added E2E test for deleting supplies in inventories (Ilyass)
=> e2etest/invt-ilyassg: Added E2E test for deleting supplies in inventories

petclinic-frontend/tests/productspage/searchProduct.spec.ts
`Search method. When typing h in the search bar, horse saddle must be showed. `
=> Product Search Bar

docs/scrum-agile.md
**JIRA:** N/A
Make the doc better.
- Removed the link
=> doc(CPC) : Removed unwanted link in DoD

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VisitController.java, petclinic-frontend/src/features/visits/Review/ReviewList.tsx, petclinic-frontend/src/features/visits/VisitListTable.tsx
**JIRA:** [VIST – Restrict Admin from Managing Reviews](https://champlainsaintlambert.atlassian.net/browse/CPC-1520)
This ticket prevents Admin users from managing customer reviews. This change is necessary to ensure fairness. Admins should not be able to alter or remove customer opinions. 
No. This PR does not change anything in the .vscode folder. 
This can be bullet point or …
=> feat(VIST-CPC-1520): update edit review permissions for admin

mailer-service/Dockerfile
**JIRA:** N/A
The deployed is failing to build for the same reason the CI/CD failed.
- Bumped Go version to 1.24
=> **URGENT** bug(CPC): Deployed version failling to build

petclinic-frontend/src/features/bills/AdminBillsListTable.css
**JIRA:** https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15/backlog?selectedIssue=CPC-1447&text=BILL
A bug removed my changes for the front-end
Redid my work.
Same as last push
=> bug/(BILL-CPC-1447): Issue with previous pr.

petclinic-frontend/src/layouts/AppFooter.css, petclinic-frontend/src/layouts/AppFooter.tsx, petclinic-frontend/src/pages/Contact/Contact.css, petclinic-frontend/src/pages/Contact/Contact.tsx
**JIRA:** [link](https://champlainsaintlambert.atlassian.net/browse/CPC-1594)
Upon pushing a previous ticket to main, prod's footer suddenly had many misalignments. This ticket is about resolving those misalignments while also fixing any other issues that exists such as the emojis not being in a unicode format. This is a hot-patch.
No changes to `.vscode`.
- **Home**: Emoji's have been replaced with unicode format.
- **Footer**: Footer CSS and JSX, Emoji's have been replaced with unicode format.
- **Contact**: Emoji's have been replaced with unicode format.
- 
No changes to any API calls.
No. Reuses existing endpoints; no new service-to-service calls. (No C4 L2 updates required.)
**Before:**
**After:**
The "Update User Experience" epic should be complete with this addition.
[ …
=> Fix footer field misalignment and replace emojis

visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DomainClientLayer/Mailing/OldMail.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/MailServiceTests.java
**JIRA:** [link](https://champlainsaintlambert.atlassian.net/browse/CPC-1591?atlOrigin=eyJpIjoiM2QyMDljNGIzYmVmNDlhNzk1MzU0OTdiMTY2NmQzNGQiLCJwIjoiaiJ9)
Made the mailer DTO, service and service impl inside the visits service up to date with the mailer service
no front end touched
- Created new Mail DTO that matches the mailer service
- Updated the tests for the mailing folder in visits service
- Changed the generateVisitRequestEmail method inside visitServiceImpl to work with the new mailing service
NA
No
Does not change UI
Use the generateVisitRequestEmail method to work with the add review method to get it to send an email when you add an …
=> Bug(AUTH-CPC-1591): Implemened the new go mailer structure for the go mailer in visits

docker-compose.prod.yml
fixing prod
If the PR uses the v2 API, explain why
If the PR adds a new communication between services, make sure to update the C4 L2. …
=> merge from main and change profile from prod to docker

petclinic-frontend/src/features/visits/Emergency/Model/EmergencyResponseDTO.ts, petclinic-frontend/src/features/visits/VisitListTable.css, petclinic-frontend/src/features/visits/VisitListTable.tsx
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1567
No.
This PR changes the look of the admin panel for the visits page. This mainly changes the CSS for the tables as well as the layout, as well as adding buttons. This PR also fixes the search bar feature to make it functional. This PR also fixes the header of the Emergencies page.
No.
No.
Before
After
=>  fix(VIST-CPC-1567): Fix CSS for Visits Front Page Tables

docker-compose_no_FE.yml
**JIRA:**https://champlainsaintlambert.atlassian.net/browse/CPC-1684
There was a leftover line causing the file not to work
no
removed the unnecessary line
no
no
no
=> bug(AUTH-1648) Fix the docker-compose-no-FE not working

auth-service/src/main/java/com/petclinic/authservice/businesslayer/UserServiceImpl.java, auth-service/src/main/resources/application.yml
**JIRA:**  https://champlainsaintlambert.atlassian.net/browse/CPC-1605
the tests were failing for the auth service pipeline
no
added a default configuration so that the tests wont fail
no
no
=> Bug(AUTH-CPC-1605) fixed CI test pipeline failing on auth service

petclinic-frontend/src/features/home/components/VetCard.css
**JIRA:** [link](https://champlainsaintlambert.atlassian.net/browse/CPC-1620)
This ticket essentially makes the smallest one line code fix where I added `margin: auto;` in the css to align the vet-body in center. This is nothing massive, it might be the smallest PR, this was more or less a hotfix for front-end
No changes to `.vscode`.
No changes to any API calls.
No. Reuses existing endpoints; no new service-to-service calls. (No C4 L2 updates required.)
**Before:**
**After:**
=> bug(AUTH-CPC-1620): Fix vet card body misalignment on home page

auth-service/src/main/java/com/petclinic/authservice/businesslayer/UserServiceImpl.java, auth-service/src/main/resources/application.yml
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1605
The angular page is inaccessible to users
no
Changed the docker compose since some of the values might be called in the api-gateway
no
no
no
=> bug(AUTH-CPC-1605) fixed the angular page not being accessible on prod

petclinic-frontend/src/features/visits/Emergency/AddEmergencyForm.tsx, petclinic-frontend/src/features/visits/Emergency/Api/addEmergency.ts
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1647?atlOrigin=eyJpIjoiNDdiN2U0NTRmYzhhNGJhMDlkZDUzNTYzMjQ3YTU2YWUiLCJwIjoiaiJ9)
This ticket fixes an issue where users get an error when trying to add an emergency visit. The change makes sure that the “Add Emergency Visit” now works as intended.
No. …
=> bug(VIST-CPC-1647): fix post emergency visit
