cgerard321/champlain_petclinic

visits-service/build.gradle, visits-service/lombok.config, visits-service/src/main/java/com/petclinic/visits/presentationlayer/VisitResource.java, visits-service/src/test/java/com/petclinic/visits/businesslayer/VisitsServiceImplTests.java, visits-service/src/test/java/com/petclinic/visits/presentationlayer/VisitResourceTest.java
* Changed the minimum code coverage to 90% in build.gradle
* Added a new file called lombok.config that has a configuration for Lombok to add a generated annotation to generated methods which will be ignored for testing code coverage by Jacoco
* Added missing tests to bring code coverage to 100%
This shouldn't break main.
All that's left is for @lbains to merge his fix for his PUT mapping (CPC-212) and the code coverage will become 100%. (It's 98% without his fix)
=> conf(VISE-CPC-282): Configuring Lombok to ignore auto generated methods for Jacoco

visits-service/src/main/java/com/petclinic/visits/businesslayer/VisitsService.java, visits-service/src/main/java/com/petclinic/visits/businesslayer/VisitsServiceImpl.java, visits-service/src/main/java/com/petclinic/visits/datalayer/VisitRepository.java, visits-service/src/main/java/com/petclinic/visits/presentationlayer/VisitResource.java, visits-service/src/main/resources/data-h2.sql, visits-service/src/main/resources/data-mysql.sql, visits-service/src/test/java/com/petclinic/visits/businesslayer/VisitsServiceImplTests.java, visits-service/src/test/java/com/petclinic/visits/datalayer/PersistenceTests.java, visits-service/src/test/java/com/petclinic/visits/presentationlayer/VisitResourceTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-159?atlOrigin=eyJpIjoiZGVkYjViMWExNTk1NGM5MmFhZjMxMzZjZWEzZWY1MTUiLCJwIjoiaiJ9
- Our service now has a GET mapping for fetching previous visits only and a GET mapping for fetching scheduled visits only (for a specific pet).
- Added a method in the business layer to filter out unwanted visits based on a boolean and the date and time when the request is made.
- Added tests for those methods.
- Fetching visits with a negative petId will now throw an InvalidInputException which is handled gracefully.
=> feat(VISE-CPC-159): Fetch previous and scheduled visits separately

billing-service/src/main/java/com/petclinic/billing/businesslayer/BillServiceImpl.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java
JIRA: https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15?modal=detail&selectedIssue=CPC-449&assignee=6005c6881ffcc00076745e8b
Configure logic for a not found visit type. The code for the visit type to price was done in sprint 2 but I realized we were missing logic for when a visit type is not found in our list of possible visit type
Changed the tests and added to the CreateBill method of Billing service which now throws and exception if the get to the hashmap returns null
=> bug(BILL-CPC-449): Configure logic for a not found visit type

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/VisitDetails.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-331
This ticket will implement the request to get previous visits of a pet and also the corresponding mapping in the API gateway controller.
Added the method in the VisitsServiceClient.
Added the mapping in the BFFApiGatewayController.
Added Controller Testing.
Added Integration Testing.
No changes have been done to the UI.
=> feat(APIG-CPC-331): Get request for previous visits of a pet

customers-service/src/test/java/com/petclinic/customers/presentationlayer/OwnerPersistenceTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-686?atlOrigin=eyJpIjoiZWQ4Y2Q1OWViMzRiNGFlMjhmNmJkYmQxMzExNWI5YTMiLCJwIjoiaiJ9
update test had a chance to fail depending in what order tests ran since it would save with the wrong id
I resigned the generated id on save to the local object to which we are comparing the saved one
=> bug/ACMS-CPC-686_OwnerPersistenceupdate_owner_test not saving Id correctly

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java, api-gateway/src/main/resources/application.yml, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java, docker-compose.yml, settings.gradle, visits-service-new/build.gradle, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitController.java, visits-service-new/src/main/resources/application.yml
Removed unused imports.
Files updated to support the reactive visists-service. This affects only the VisitsServiceClient by starting the process of using the reactive visits-service.
Disabled 2 containers, the old non-reactive visits-service and its connected database mysql1, making the project quicker to build.
No UI change.
The VisitsServiceClient is now using the reactive visits-service but still needs to be worked on to make it fully reactive. The non-reactive visits-service is disabled.
Disabled the non-reactive visists-service, replacing it in the api-gateway with the reactive version of it.
=> conf(VIST-CPC-769): edit files to disable non reactive version of visits service

visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/VisitRepo.java
JIRA: [CPC-759](https://champlainsaintlambert.atlassian.net/browse/CPC-759)
A String document type should be used instead of Integer.
Changed the visits repo type to String.
No UI change.
This was separate in its own pull request since multiple people rely on this change for the database to work properly.
=> bug(VIST-CPC-759): fixed visits repository to use String data type as document identifier

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/vet-list/vet-list.controller.js, api-gateway/src/main/resources/static/scripts/vet-list/vet-list.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/RatingRepository.java, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/RatingService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/RatingServiceImpl.java, vet-service/src/test/java/com/petclinic/vet/dataaccesslayer/RatingRepositoryTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-728?atlOrigin=eyJpIjoiNmQ3OTU5Y2VkNmU3NDk3NGE2MDBlZWQzZjExYmQyYzQiLCJwIjoiaiJ9
We want to display the total number of ratings each vet has. Doing this allows the user to quickly see how many ratings a certain vet has. 
- Implementation of a get number of ratings per vet in Api-Gateway
- Implementation of get number of ratings per vet in the Vet-Service
- 90% + testing in Api-gateway
- 90% + testing in Vet-Service
- Front-end Implementation: now displays the number of ratings per vet next to the vet's information
=> Feat(VETS-CPC-728): get number of vet ratings for each vet

api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Bills/BillDetails.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Bills/BillRequestDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Bills/BillResponseDTO.java, api-gateway/src/main/resources/static/scripts/bill-history/bill-history.template.html, billing-service/src/main/java/com/petclinic/billing/datalayer/Bill.java, billing-service/src/main/java/com/petclinic/billing/datalayer/BillDTO.java, billing-service/src/main/java/com/petclinic/billing/datalayer/BillRequestDTO.java, billing-service/src/main/java/com/petclinic/billing/datalayer/BillResponseDTO.java, billing-service/src/main/java/com/petclinic/billing/datalayer/DataSetupService.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java, billing-service/src/test/java/com/petclinic/billing/datalayer/BillServicePersistenceTests.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceIntegrationTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceUnitTest.java
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-743)
I needed to make the date visible when looking at the bills
- I changed the name of the date variable from visitsDate to date, to make it match the name that was in BillDetails in the API-Gateway.
- I changed the date type to LocalDate()
- I changed the UI to only say Date 
- We can now see the date.
- The "Date\Time" subtitle is now changed to "Date".
Before:
After:
=> bug(BILL-CPC-743): made date visible and change Date type to LocalDate

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.controller.js, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/RatingRepository.java, vet-service/src/main/java/com/petclinic/vet/exceptions/GlobalControllerExceptionHandler.java, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/RatingService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/RatingServiceImpl.java, vet-service/src/test/java/com/petclinic/vet/dataaccesslayer/RatingRepositoryTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java
Update rating for vet by vetId and ratingId implemented
CPC-744
https://champlainsaintlambert.atlassian.net/browse/CPC-744
This ticket implements the update rating of a vet by vetId and ratingId in the vet-service and api-gateway. The user is now able to edit their ratings if they want to go back on them. Although they aren't able to see the rating description they added yet, it will be displayed in the near future. 
- The "updateRatingByVetIdAndByRatingId" method was implemented in VetsServiceClient, BFFApiGatewayController, VetController, RatingService, and RatingServiceImpl.
- The "vet-details.component.js" has been updated to be able to update an existing rating with its ratingId and rating data from the update form fields.
- The "vet-details.template.html" …
=> feat(VETS-CPC-744): Update rating for vet by vetId and ratingId implemented

api-gateway/src/main/resources/static/scripts/vet-list/vet-list.controller.js, api-gateway/src/main/resources/static/scripts/vet-list/vet-list.template.html
**JIRA:** https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/35?selectedIssue=CPC-849&sprints=293
This bug is fixed in order to see the AverageRating and the NumberOfRating appear when choosing  a filter between All, Active or Inactive in the vetenerian main page 
- Modification of the ReloadData function in the veterinarian-list controller frontend
**ALL, ACTIVE AND INACTIVE PAGES LOOKED THE SAME**
**ALL FILTER:**
**ACTIVE FILTER:**
**INACTIVE FILTER:**
=> bug(VETS-CPC-849) display AverageRating and NumberOfRating when vets are filtered

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/visit-list/visit-list.controller.js, api-gateway/src/main/resources/static/scripts/visit-list/visit-list.js, api-gateway/src/main/resources/static/scripts/visit-list/visit-list.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
https://champlainsaintlambert.atlassian.net/browse/CPC-787
This ticket is about fixing and properly implementing the delete visit by visitId functionality in the front-end.
- Changes made to visit-list script files to enable delete visit functionality via the front-end
- Tests added to ApiGatewayControllerTest file
Delete visit message pop-up
Delete success pop-up
Updated visit list
=> feat(VIST-CPC-787): Implementing delete visit functionality in the front-end

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Vets/EducationRequestDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Vets/EducationResponseDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.controller.js, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/Education.java, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/EducationRepository.java, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/DataSetupService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/EducationRequestDTO.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/EducationResponseDTO.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/EducationService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/EducationServiceImpl.java, vet-service/src/main/java/com/petclinic/vet/util/EntityDtoUtil.java, vet-service/src/test/java/com/petclinic/vet/dataaccesslayer/EducationRepositoryTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/EducationServiceImplTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-938?atlOrigin=eyJpIjoiMWU4YjU0ZjBhN2UwNDU5ZTg2MzBlZGRlMDYwOWE5ZDciLCJwIjoiaiJ9
Displays all the different educations that a vet has. 
I created the Education entity, and implemented the get request in vets-service and api-gateway. Completed testing for getAllEducationsPerVetId in both vets service and API gateway. Implemented a working front-end that displays all the education that a vet has.
=> feat(VETS-CPC-938): get all educations of a vet

api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitDetails.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitRequestDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitResponseDTO.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitService.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/DataSetupService.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/Visit.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitRequestDTO.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitResponseDTO.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/DataLayer/VisitRepoTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitControllerUnitTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitsControllerIntegrationTest.java
https://champlainsaintlambert.atlassian.net/browse/CPC-949
This ticket was to modify the visitDate variable's LocalDateTime format to disregard seconds and milliseconds through the use of @JsonFormat(pattern = "yyyy-MM-dd HH:mm") as well as an updated DateTimeFormatter.
- modified all date logic in visits-serivce-new 
- modified all visits tests in api-gateway
Before changes
After changes
- [pull request link](https://github.com/cgerard321/champlain_petclinic/pull/408)
=> feat(VIST-CPC-949): updated datetime formatter

api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/CustomerServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, customers-service-reactive/src/test/java/com/petclinic/customersservice/presentationlayer/PetControllerIntegrationTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-881
Increase jacoco coverage on the api-gateway and customer-service
Added isActive status patch testing on api-gateway and customer-service-reactive, fixed up some tests that require isActive as a variable.
Up from 94%
**Gateway Tests**
=> Bug/cpc 881 cstm   fix pet is active status and patch related tests on api gateway

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.controller.js, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/Education.java, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/EducationRepository.java, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/EducationService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/EducationServiceImpl.java, vet-service/src/test/java/com/petclinic/vet/dataaccesslayer/EducationRepositoryTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/EducationServiceImplTest.java
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/13?selectedIssue=CPC-941)
This ticket is about implementing the function of deleting an education of a vet via a delete button
- Education entity
- Implemented delete education in vet-service and Api gateway
- Completed testing for deleteEducationByVetId in both vet service and API gateway
- Implemented a working front-end that deleted a specific education of a vet
Before
After
Result of delete
=> feat/(VETS-CPC-941): Delete vets education implemented

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/Status.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/visit-list/visit-list.controller.js, api-gateway/src/main/resources/static/scripts/visit-list/visit-list.js, api-gateway/src/main/resources/static/scripts/visit-list/visit-list.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitService.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/DataSetupService.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/Status.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitController.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitControllerUnitTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitsControllerIntegrationTest.java
https://champlainsaintlambert.atlassian.net/browse/CPC-947
This ticket pertains to implementing a new functionality in the frontend that allows for the user to delete all cancelled visits from the database. This functionality compliments our teams newly incorporated Cancel Visit functionality.
- deleteAllCancelledVisits method logic implemented in the backend
- successful and exception test cases implemented in the frontend and backend test classes
- UI styling touchups
Before changes:
After changes:
- Our team has decided that we will be making some minor changes to the separation logic regarding the Upcoming and Previous visits. Will be introduced in upcoming pull requests.
[- pull request link](https://github.com/cgerard321/champlain_petclinic/pull/489)
=> feat(VIST-CPC-947): implement delete all canceled visits functionality

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/Inventory-form/inventory-form.controller.js, api-gateway/src/main/resources/static/scripts/inventory-list/inventory-list.controller.js, api-gateway/src/main/resources/static/scripts/inventory-list/inventory-list.template.html, api-gateway/src/main/resources/static/scripts/inventory-update-form/inventory-update-form.controller.js, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClientIntegrationTest.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java, inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java, inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java, inventory-service/src/main/java/com/petclinic/inventoryservice/utils/DataBaseLoaderService.java, inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java, inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/CPC-895
This ticket is about adding the rendering of all created inventory types after creating them.
- This affects the inventory
- This affects the addition and editing of inventories
- Added get all inventory type request
- Displays all the default + custom inventory types in the dropdown bar
- Search queries now support the custom inventory types as well + displayed when clicked on
- All testing required is completed
Before
After
Add Form
Update Form
https://github.com/cgerard321/champlain_petclinic/pull/505
=> feat(INVT-CPC-895): Get all custom inventory types

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java, api-gateway/src/main/resources/static/scripts/visit-list/visit-list.controller.js, api-gateway/src/main/resources/static/scripts/visit-list/visit-list.template.html, api-gateway/src/main/resources/static/scripts/visits/visits.controller.js
https://champlainsaintlambert.atlassian.net/browse/CPC-913
This ticket is regarding making updates to the Visit-List UI. Our team thought it would be an interesting idea to separate visits into more than just a single table and, to compliment our recent implementations of status-button functionalities, we thought it would be best for these tables to be based on visit status. We now have a total of four tables: Upcoming Visits, Confirmed Visits, Cancelled Visits and Completed Visits. 
- Tweaks to the controller.js file were made to push visitData to the appropriate status table
- Three new status tables were added to the html template (aside from our original upcoming visits table that was previously implemented)
- Styling modifications were made to make the UI …
=> feat(VIST-CPC-913): sorting visits into status tables

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Auth/RegisterVet.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Vets/VetAverageRatingDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Vets/VetRequestDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Vets/VetResponseDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/RequestContextAdd.java, billing-service/src/main/java/com/petclinic/billing/datalayer/VetResponseDTO.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetRequestDTO.java, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetResponseDTO.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/VetAverageRatingDTO.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/VetService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/VetServiceImpl.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/ratings/RatingServiceImpl.java, vet-service/src/main/java/com/petclinic/vet/util/EntityDtoUtil.java, vet-service/src/main/resources/schema.sql, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/VetServiceImplTest.java
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-838?atlOrigin=eyJpIjoiZDY2NjY4YWUyYmQzNGRhNWEwY2YyZGZhZDI0MGFkMDAiLCJwIjoiaiJ9
The vet-service only had a VetDTO, so I split it into a VetRequestDTO and a VetResponseDTO to follow better practice.
- The DTO was split
- All calls to the VetDTO in the vet-service was changed to use the response and request DTOs appropriately
- The tests in the vet-service were updated to use the request and response DTOs
- All calls to the VetDTO in the api-gateway was changed to use the response and request DTOs appropriately
- The tests in the api-gateway were updated to use the request and response DTOs
=> feat(VETS-CPC-838): split vet dto

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Vets/RatingResponseDTO.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.controller.js, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/ratings/Rating.java, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/DataSetupService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/ratings/RatingResponseDTO.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/ratings/RatingService.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/ratings/RatingServiceImpl.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/RatingServiceImplTest.java
JIRA:https://champlainsaintlambert.atlassian.net/browse/CPC-835
This feature is to be able to get all the ratings for each vet depending on the year entered by the user.
90% Vet-Service Coverage
90% Coverage of feature in API-Gateway
Added a search query in vet details
Before:
After:
=> feat(VETS-CPC-835): Get all ratings older and newest by year

api-gateway/src/main/resources/static/scripts/vet-details/vet-details.controller.js, api-gateway/src/main/resources/static/scripts/vet-details/vet-details.template.html
CPC-996
https://champlainsaintlambert.atlassian.net/browse/CPC-996
This ticket is about fixing a bug: when selecting a predefined description for the rating of a vet, the predefined description cannot be unchecked (if the user decides to write a custom description). The radio buttons had to be changed to checkboxes (because radio buttons cannot be unselected) while also ensuring that only one checkbox can be checked at a time (keeping track of the most recently checked checkbox).
- Change radio button to checkbox in vet-details.template.html.
- Add function that ensures that only one checkbox can be checked at a time (keeping track of the most recently checked checkbox) in vet-details.controller.js.
- pull request …
=> bug(VETS-CPC-996): fix predefined description of vet rating: rating cannot be unchecked

api-gateway/src/main/resources/static/scripts/visit-list/visit-list.controller.js, api-gateway/src/main/resources/static/scripts/visit-list/visit-list.template.html
link to JIRA ticket:
https://champlainsaintlambert.atlassian.net/browse/CPC-997
This ticket is pertaining to adding the ability to collapse the visit status tables. This ticket was inspired by a discussion in a scrum meeting when analyzing the implemented status tables sorting. The possibility of our user (secretary in this case) needing to scroll through many visits before reaching another status table is unlikely, but is a possibility to take into account nonetheless. This inspired this UI adjustment.
- Adding a boolean scope to the visit-list controller for each status table
- Adding 'Collapse Arrow Buttons' to each table header
Before Changes:
After Changes:
- Collapsed Table View (Upcoming)
- Closed Table View (Upcoming)
- Header, Arrows & Table hidden when visits in table reaches 0 …
=> feat(VIST-CPC-997): make status tables collapsible

api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/BillServiceClientIntegrationTest.java
JIRA: (https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/35?selectedIssue=CPC-920&sprints=315)
This ticket involves adding negative tests to the BillServiceClient integration tests to assess how the system behaves under the wrong conditions, ensuring reliability and error handling.
- getNonExistentBillById
- getBillByInvalidVetId
- getBillsByInvalidCustomerId
- deleteNonExistentBill
- deleteBillWithInvalidVetId
- deleteBillWithInvalidCustomerId
- createBillWithInvalidRequest
=> bug(BILL-CPC-920) Implement Negative Testing In BillServiceClientIntegration tests

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/DuplicateTimeException.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java, docker-compose.yml, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/VisitRepo.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/Exceptions/DuplicateTimeException.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/Exceptions/GlobalControllerExceptionHandler.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/Exceptions/GlobalControllerExceptionHandlerTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitsControllerIntegrationTest.java
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1005)
This ticket is needed to ensure that there is only 1 visit for a specific time for a vet and blocking new visit appointments from being created if there is 
- Added a new Exception (DuplicateTime Exception) to the back end and api-gateway
- Added an error message to display if a user attempts to create a visit at the same time as another visit for a vet
- Added testing for the new exception in the api-gateway and back end 
- Testing for the new methods are at 100%
=> feat(VIST-CPC-1005): ensure no duplicate visit time

api-gateway/src/main/resources/static/index.html, api-gateway/src/main/resources/static/scripts/inventory-list/inventory-list.template.html, api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.template.html
https://champlainsaintlambert.atlassian.net/browse/CPC-988
This change is about re styling the inventory action handlers.
- Added different animated icons from library set in the index
- Added titles when hovering the buttons
- This change only affects the styling of the action handlers
- Equalized the list borders
InventoryProducts-Before
InventoryProducts-After
Inventory-Before
Inventory-After
=> Feat(INVT-CPC-988): Include user friendly action handlers

api-gateway/src/main/resources/static/scripts/inventory-list/inventory-list.controller.js, api-gateway/src/main/resources/static/scripts/inventory-list/inventory-list.template.html, api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.controller.js, api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.template.html
https://champlainsaintlambert.atlassian.net/browse/CPC-986
This ticket is about the ability to clear all input fields 
- Added Clear queries action handler
- This affects both inventory and the product list
- Will simply clear the input fields, then reset the list automatically
- Added related icon
Inventory-Before
Inventory-After
Product list-Before
Product list-After
=> Feat(INVT-CPC-986): Ability to clear all search input fields

api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitResponseDTO.java, api-gateway/src/main/resources/static/index.html, api-gateway/src/main/resources/static/scripts/app.js, api-gateway/src/main/resources/static/scripts/visit-details-info/visit.component.js, api-gateway/src/main/resources/static/scripts/visit-details-info/visit.controller.js, api-gateway/src/main/resources/static/scripts/visit-details-info/visit.details.template.html, api-gateway/src/main/resources/static/scripts/visit-details-info/visit.js, api-gateway/src/main/resources/static/scripts/visit-list/visit-list.template.html, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, docker-compose.yml, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/DataSetupService.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitResponseDTO.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/Utils/EntityDtoUtil.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/VisitsServiceNewApplication.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/DomainClientLayer/PetsClientUnitTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/DomainClientLayer/VetsClientUnitTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitsControllerIntegrationTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/Utils/EntityDtoUtilTest.java
JIRA:[ link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-927)
Visits only had access to the petId and vetId. By aggregating it, we now have access to the needed vet information and pet information. There was also no details page for our visits. The user only had access to the general view which is a list.
This also allows us to populate a details page with a single get method. 
-Changed visitResponseDTO to now have the vet's full name and contact information as well as the pet's birth date and name.
-Added navigation to Details Page
-Added Details Page to the front-end
UI CHANGES:
**BEFORE:**
**AFTER:**
DETAILS PAGE:
=> feat(VIST-CPC-927): implementing aggregation and details page

billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java
JIRA: https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15/backlog?selectedIssue=CPC-934
This ticket involves adding negative tests to the BillServiceImplTest to ensure that the service behaves correctly when encountering various error scenarios.
Created 6 negative tests,
-	test_getBillByNonExistentBillId
-	test_updateNonExistentBillId
-	test_deleteNonExistentBillId
-	test_updateBillWithInvalidRequest
-	test_GetBillByNonExistentCustomerId
-	test_CreateBillWithInvalidData
=> feat(BILL-CPC-934) Implement Negative Testing in BillServiceImplTest

api-gateway/src/main/resources/static/scripts/visit-list/visit-list.template.html
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-925)
The list displayed many non user friendly data such as the vetId and petId that are UUIDS. By displaying the vet's and pet's names instead of their Id, our website becomes more user-friendly.
Changed the front-end to display vet name and pet name instead of their Ids
UI CHANGES
**BEFORE**
**AFTER**
=> feat(VIST-CPC-925): changing vet id and pet id to vet name and pet name in the visits-list page

api-gateway/src/main/resources/static/scripts/product-details-info/product-details-info.template.html
https://champlainsaintlambert.atlassian.net/browse/CPC-994
- I modified the styling to get product details 
- Added a card element to display the details in a card format
- removed the box and the lines that was surrounding the text
Before 
After
=> FEAT(INVT-CPC-994): fixed the styling of products details page bug

api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/Utils/EntityDtoUtilTest.java
link to jira ticket:
https://champlainsaintlambert.atlassian.net/browse/CPC-817
This ticket pertains to adding some missing tests for the EntityDTOUtils class in the visits-serivce as well as a missed method in the VisitsServiceClient.
- Added testToVisitEntity
- Added test deleteVisitByVisitIdShouldSucceed
Teammate will be making a pr shortly adding more tests for coverage
=> bug(VIST-CPC-817): add missing tests for entityDtoUtil and visitsServiceClient

api-gateway/src/main/resources/static/index.html, api-gateway/src/main/resources/static/scripts/app.js, api-gateway/src/main/resources/static/scripts/auth/admin-panel/admin-panel.template.html, api-gateway/src/main/resources/static/scripts/auth/update-role-form/role-update.component.js, api-gateway/src/main/resources/static/scripts/auth/update-role-form/role-update.config.js, api-gateway/src/main/resources/static/scripts/auth/update-role-form/role-update.controller.js, api-gateway/src/main/resources/static/scripts/auth/update-role-form/role-update.service.js, api-gateway/src/main/resources/static/scripts/auth/update-role-form/role-update.template.html, auth-service/src/main/java/com/petclinic/authservice/businesslayer/UserService.java, auth-service/src/main/java/com/petclinic/authservice/datalayer/user/UserRepo.java, auth-service/src/main/java/com/petclinic/authservice/presentationlayer/User/RolesChangeRequestDTO.java, auth-service/src/test/java/com/petclinic/authservice/presentationlayer/User/UserControllerIntegrationTest.java
https://champlainsaintlambert.atlassian.net/browse/CPC-755
This ticket is about adding three roles, and one of them to be assigned to users because we want them to have a restricted access in the system. It is also about the feature for the admin to update the users' role if ever a user needs a different permission on the website.
- A new column in the admin panel called "Role" to see the users' current role assigned
- A new button in the admin panel called "Update Role" to navigate to the update user role form
- A new form for updating a user's role with list of availble roles to …
=> feat(AUTH-CPC-755): Add More Roles Front End

api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1015)
This ticket is to fix/add the testing for the service and the controller in the api-gateway to improve the code coverage and cover some of the methods.
- Added testing for api-gateway controller and now all visits methods are tested
- VisitsServiceClient is 85%
=> bug(VIST-CPC-1015): add more coverage to api-gateway tests

petclinic-frontend/src/pages/Login/Login.tsx, petclinic-frontend/src/router.tsx, petclinic-frontend/src/shared/models/path.routes.ts
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1123
When a user logs in, they are redirected to the inventories page. This is problematic because if the user isn't an inventory manager or an admin, they will be unauthorized. Also, users should land on the home page when logging in, not the inventories page.
- Redirects users to the home page after logging in
- Changed the routing from Inventories to Home
=> bug/(AUTH-CPC-1123): Redirect users to home page after login

petclinic-frontend/src/pages/Error/ErrorPage.css, petclinic-frontend/src/pages/Error/Forbidden.tsx, petclinic-frontend/src/pages/Error/InternalServerError.tsx, petclinic-frontend/src/pages/Error/PageNotFound.tsx, petclinic-frontend/src/pages/Error/RequestTimeout.tsx, petclinic-frontend/src/pages/Error/ServiceUnavailable.tsx, petclinic-frontend/src/pages/Error/Unauthorized.tsx, petclinic-frontend/src/router.tsx, petclinic-frontend/src/shared/api/axiosErrorResponseHandler.ts, petclinic-frontend/src/shared/models/path.routes.ts
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1129
We currently do not have custom error pages.
- Created error pages for status code: 401, 403, 404, 408, 500, and 503.
- Button to go back home.
- Added some styling (might change in future). All pages use the same design.
- Routed all the pages accordingly.
**Before**
**After**
The other error pages look the same with their corresponding messages.
=> feat/(AUTH-CPC-1129): Create error pages for 4xx and 5xx status codes

.gitignore, petclinic-frontend/.gitignore, petclinic-frontend/.vscode/.editorconfig, petclinic-frontend/.vscode/extensions.json, petclinic-frontend/.vscode/settings.json, pull_request_template.md
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1137
VSCode configuration and extensions for esLint and Prettier were removed. 
- updated global .gitignore
- updated petclinic-frontend .gitignore
- added .vscode folder in petclinic-frontend
- added three configuration files in .vscode folder
N/A
N/A
https://github.com/cgerard321/champlain_petclinic/pull/619
https://github.com/cgerard321/champlain_petclinic/pull/631
=> conf(CONF-CPC-1137): re-add VSCode extensions

petclinic-frontend/src/context/UserContext.tsx, petclinic-frontend/src/features/customers/components/UpdateCustomerForm.css, petclinic-frontend/src/features/customers/components/UpdateCustomerForm.tsx, petclinic-frontend/src/layouts/AppNavBar.tsx, petclinic-frontend/src/pages/Customer/AddingCustomer.css, petclinic-frontend/src/pages/Customer/AddingCustomer.tsx, petclinic-frontend/src/pages/Customer/ProfileEdit.tsx, petclinic-frontend/src/router.tsx, petclinic-frontend/src/shared/components/ProtectedRouteProps.tsx, petclinic-frontend/src/shared/hooks/useHasRequiredRole.ts, petclinic-frontend/src/shared/models/Role.ts, petclinic-frontend/src/shared/models/UserResponseModel.ts
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1134
Currently, users can access every page that the axiosErrorResponseHandler doesn't handle. This means that an admin or vet is able to access the customer profile edit page which only a customer should be able to see.
Absolutely not. I hope.
- Created a hook to validate user roles (useHasRequiredRole.ts). Implemented it in the ProtectedRouteProps.tsx
- Added the roles that are authorized to access ProfileEdit, AddingCustomer, and AllOwners. Other teams can implement it to their pages as well (see dev notes).
- Created 4 additional functions that people can use in the UserContext.tsx
- Refactored and reorganized the ProfileEdit.tsx. The update form is now a component in the newly created components folder in …
=> feat/(CUST-CPC-1134): Render pages based on user roles

petclinic-frontend/src/features/products/api/getAllProducts.ts
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1142
After the following [commit](https://github.com/cgerard321/champlain_petclinic/commit/a2c737d0810c795f601678aaf9df4303ee92f896), the Products page was broken due to getAll being changed to a fetcher that expects a APPLICATION_JSON format but the backend returns an EVENT_STREAM.
- Revert getAllProducts to previous version (event-stream implementation)
Before:
After:
Please don't change getAllProducts implementation, this one is fine.
Thank you. …
=> bug(PROD-CPC-1142): revert products getall

petclinic-frontend/src/router.tsx
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1143
The PR https://github.com/cgerard321/champlain_petclinic/pull/665 accidentally removed the roles for the pages that were added in PR https://github.com/cgerard321/champlain_petclinic/pull/656. This was done in the file router.tsx.
No
- Reverted the change
- Moved PageNotFound to where it should be
https://github.com/cgerard321/champlain_petclinic/pull/656
https://github.com/cgerard321/champlain_petclinic/pull/665
=> bug/(CUST-CPC-1143): Add back roles for pages that were accidentally removed

petclinic-frontend/src/features/visits/VisitListTable.css, petclinic-frontend/src/features/visits/VisitListTable.tsx, petclinic-frontend/src/pages/Visit/Visit.tsx, petclinic-frontend/src/pages/Visit/Visits.css
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1167)
Implementing a cleaner and organized UI design to the visits section. Now the visits will be displayed in different tables based on their status.
No, it doesn't change the .vscode.
The buttons are now separated from one another.
The visits table are separated by upcoming, completed and confirmed visits.
Added padding to the page container. 
Before:
After:
=> feat/(VIST-CPC-1167): Update UI for visits section

petclinic-frontend/src/features/inventories/InventoriesListTable.tsx
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1149
Fixed the inventory pages going on infinitely, as well as their ugly CSS.
No, it does not
- Fixed the prevPage and nextPage buttons CSS by adding a different styling to the current bootstrap buttons
- Added contraints to block the nextPage button if there are no inventories on it.
Before:
After:
=> bug(INVT-1149) Fix inventory pages

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/CustomersServiceClient.java, auth-service/build.gradle, auth-service/src/main/java/com/petclinic/authservice/businesslayer/UserServiceImpl.java, auth-service/src/test/java/com/petclinic/authservice/presentationlayer/User/UserControllerIntegrationTest.java, petclinic-frontend/src/pages/User/SignUp.tsx
[**JIRA:** link to jira ticket](https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15/backlog?selectedIssue=CPC-1188)
We are doing this change because Christine requested the change to the older mailing service and because there was a small bug with the v2 endpoint for creating an owner account.
It doesn't do any changes to the vscode folder
- Reverted back to the old emailing service at Christine's request
- Fixed a small bug with the v2 endpoint for creating a customer as it was overwriting the UUID
- Upped Jacoco minimum % to 90
- Changed to v2 endpoint since the bug was fixed
Didn't Impact UI
There should no …
=> Bug(CUST-CPC-1188): Fixed V2 endpoint for creating a user failing and reverted back to old emailing service

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/CustomersServiceClient.java
https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15/backlog?selectedIssue=CPC-1188
My previous pull request broke the add owner and I recently found out so I fixed it
It doesn't go NEAR the .vscode foler :)
Changed the CustomersServiceClient to set a UUID if when sending a request it is null or empty. It does not reset it if it is not.
Didn't affect front end, but here was the issue: 
It is now fixed
=> Bug(CUST-CPC-1188): Fixed lost UUID when creating an owner account as an admin

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/BillController.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VetController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/BillControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/BillControllerUnitTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/VetControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigBillService.java, petclinic-frontend/src/features/bills/AdminBillsListTable.tsx, petclinic-frontend/src/features/bills/api/addBill.tsx, petclinic-frontend/src/features/bills/models/BillRequestModel.tsx, petclinic-frontend/src/features/customers/api/getAllOwners.ts, petclinic-frontend/src/features/veterinarians/api/getAllVets.ts
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1234
As an admin, I should be able to create a bill, in case of unforeseen problem, emergency  or manual entry is required. 
Acceptance Criteria:
1. Admin should have an option (a button of some kind) to start the bill creation process.
2. A form for creating the bill should be displayed.
3. Inserting incorrect information should return an error and shouldn’t create the bill
4. Putting in all the correct information, the bill should be created and the form should disappear.
5. The new bill can now be seen and is created.
It does not.
- added 2 api function for a get all in vets and customers in the front-end.
- added a post function in the v2 controller.
- added testing for the post function
- modified the vets get all vets …
=> feat(BILL-CPC-1234): Admin Can Create Bill

petclinic-frontend/src/features/products/TrendlingList.tsx, petclinic-frontend/src/features/products/components/Product.tsx
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1263)
In the main shop page it would list all of the product information even if it would take the whole page, so we decided to cut the description if it's too long and keep the description untouched in the details page.
Nope😉
- Made changes to the Product.tsx and TrendingList.tsx to know which descriptions to cut
**BEFORE**
**AFTER**
=> bug(PROD-CPC-1263): product description too long

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/Status.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VisitController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/visit/VisitControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/visit/VisitControllerUnitTest.java, petclinic-frontend/src/features/visits/VisitListTable.tsx, petclinic-frontend/src/pages/Visit/Visit.tsx, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitService.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/DataSetupService.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/Status.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitController.java, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/Utils/EntityDtoUtil.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitControllerUnitTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitsControllerIntegrationTest.java
**JIRA:** [Jira link](https://champlainsaintlambert.atlassian.net/browse/CPC-1173)
The admin will be able to archive COMPLETED visits if the status is set to completed.
No.
- Removed previous implementation of "Delete Completed Visit" and replaced with "Archive Completed Visit"
- Added a new 'Status' called 'ARCHIVED'
- Archived Button Pops up when Status is set to "COMPLETED"
- Upon archiving a completed visit, a warning pops up and waits for admin confirmation
- getVisitsForStatus switch case has been fixed by adding 'Break;'
- Made tables collapsible for a cleaner UI
BEFORE:
------
AFTER:
Collapsible table:
The previous implementation was delete completed visits, however it was recently changed to archive completed visits in order to still maintain the visit information (hence some …
=> feat(VIST-CPC-1173): Archive completed visit

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/BillServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/BillController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/BillServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/BillControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/BillControllerUnitTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigBillService.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillServiceImpl.java, billing-service/src/main/java/com/petclinic/billing/presentationlayer/BillResource.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java, billing-service/src/test/java/com/petclinic/billing/datalayer/BillServicePersistenceTests.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceIntegrationTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceUnitTest.java, petclinic-frontend/src/features/bills/AdminBillsListTable.css, petclinic-frontend/src/features/bills/AdminBillsListTable.tsx, petclinic-frontend/src/features/bills/api/deleteBill.tsx, petclinic-frontend/src/features/bills/api/getAllBillsPaginated.tsx, petclinic-frontend/src/features/bills/hooks/useGetAllBillsPaginated.ts, petclinic-frontend/src/pages/Bills/Bills.css
**JIRA:** 
https://champlainsaintlambert.atlassian.net/browse/CPC-1203?atlOrigin=eyJpIjoiNWNmOTE0ODQ3MzA1NDM5MWIzOGRhYWM0ODZiNmE2M2UiLCJwIjoiaiJ9
This feature splits all the bills in the admin page into separate pages (10 bills per page) to make the page less long.
No
- Admin bills list is split into 10 bills per page
- Created new getAllBillsPaginated method and endpoint
- Added page navigation buttons at the bottom of the page
- Added Bill Service Implementation tests
- Added Bill Resource Integration tests
- Added Bill Resource Unit tests
- Added Bill Service Client Integration tests
- Added Bill Controller Integration tests
- Added Bill …
=> feat(BILL-CPC-1203): Make pages for bills (Admin)

petclinic-frontend/src/features/bills/AdminBillsListTable.tsx
**JIRA:**
https://champlainsaintlambert.atlassian.net/browse/CPC-1299?atlOrigin=eyJpIjoiNTI0ZmU4MjVkZDIxNDM5ZmIyMDM4M2RhYWMxMDUyYWYiLCJwIjoiaiJ9
Fixed the bugs where the "Cannot delete bill" alert message would still appear after deleting a bill as well as the interpolation of billId in the successful alert message.
No.
- Removed redundant "Cannot delete bill" message in the handleDelete of AdminBillsListTable.tsx
- Fixed interpolation of billId in alert message of handleDelete in AdminBillsListTable.tsx (replaced single quotes with backticks ``)
=> bug(BILL-CPC-1299): Fix admin delete bill alert message bugs

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VetController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/VetControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigVetService.java, petclinic-frontend/src/features/veterinarians/models/EducationRequestModel.ts, petclinic-frontend/src/features/veterinarians/models/EducationResponseModel.ts, petclinic-frontend/src/pages/Vet/VetDetails.tsx
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1372
Users can now see the vets education.
No
- implemented geteducation in api gateway
- tested geteducation in api gateway
- implemented the frontend for geteducation in a list format inside the vets details
Before:
After:
=> feat(VETS-CPC-1372): get education by vet id

petclinic-frontend/src/pages/Vet/VetDetails.tsx
**JIRA:** link to jira ticket: https://champlainsaintlambert.atlassian.net/browse/CPC-1390 
before, when the profile picture was default you still had the "delete" button, which was bad for ux because you couldn't actually delete the default picture
only changed one file: vet details.tsx
If this is a change to the UI, include before and …
=> bug(VETS-CPC-1390): update delete vet profile photo button

petclinic-frontend/package-lock.json, petclinic-frontend/src/features/veterinarians/VetListCard.css, petclinic-frontend/src/features/veterinarians/VetListCards.tsx, petclinic-frontend/src/features/veterinarians/api/fetchPhoto.ts, petclinic-frontend/src/pages/Vet/Vet.tsx
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1388
On the main page of the vet, we only had a table with info such as first and last and speciality. We didn't have the picture of the vets and the page wasn't presentable. Modifications were made to have a cleaner and presentable vet page. Instead of a table we now have cards that display the first and last name, the vet specialities and their photo.
This PR does not affect the .vscode file
- Removed the vet table.
- Added cards instead of the table.
- Added the vet photos in the cards on top of the first and last names and specialities.
Before:
After:
=> feat(VETS-CPC-1388): rework vet page ui

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VetController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/VetControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigVetService.java, petclinic-frontend/src/features/veterinarians/api/updateVetEducation.ts, petclinic-frontend/src/pages/Vet/UpdateVetEducation.tsx, petclinic-frontend/src/pages/Vet/VetDetails.tsx, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitsControllerIntegrationTest.java
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1375
This PR is about updating the vets education information if ever they need to.  A new button is now accessible to all vets that, when pressed, a form with the existing vet education information will open, and vets will be able to modify it as they like.
This PR does not effect the .vscode file.
- Added the update education method in the back-end for the v2 API.
- Created tests for the method.
- Added the whole front-end logic to be able to make modifications on vet education info.
Before:
There was no button below each education information. 
After: 
=> feat(VETS-CPC-1375): update vet education information

products-service/src/main/java/com/petclinic/products/businesslayer/products/ProductServiceImpl.java, products-service/src/test/java/com/petclinic/products/businesslayer/ProductServiceUnitTest.java, products-service/src/test/java/com/petclinic/products/presentationlayer/products/ProductControllerIntegrationTest.java, products-service/src/test/java/com/petclinic/products/presentationlayer/ratings/RatingControllerIntegrationTest.java
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1414)
This ticket fixes a bug where adding a new product without ratings caused a 500 error due to a NullPointerException in the getAverageRating() method. The issue was that the averageRating was set to null, which caused problems with sorting and filtering. The fix now sets averageRating to 0.0 by default
No, this PR does not change anything in the .vscode folder.
- Updated getAverageRating() method in ProductServiceImpl.java to set averageRating to 0.0 when there are no ratings.
- Fixed tests that were causing issues.
Before:
After:
=> bug/(PROD-CPC-1414): Fix Null Average Rating Causing 500 Error on New Product Added

petclinic-frontend/src/features/products/ProductList.css
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1316?atlOrigin=eyJpIjoiODJiNjAyYjk3NDE0NDIyN2I4ZjVhOTg2N2NjM2M4YWYiLCJwIjoiaiJ9
bug where the close filter menu button would only show on hover, now fixed.
no
Added some CSS to show the button when not hovered and added some styling as well.
Before:
After:
=> bug/(PROD-CPC-1316): Product Filter Menu Close Button

auth-service/build.gradle
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15/backlog?epics=visible&selectedIssue=CPC-1280&text=Auth)
The mapper impl class was exluded in afterEvaluate testing while it shouldn't in Auth Service
It doesn't
- Removed the exclusion of mapperImpl.class in afterEvaluate in Auth service build.gradle
Everything seems to be working fine without the exclusion of it, I do not know why it has been added to the afterEvaluate in the first place
=> bug/(AUTH-CPC-1280): build.gradle should not exclude MapperImpl.class files

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VetController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/VetControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/VetControllerUnitTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigVetService.java, petclinic-frontend/src/features/veterinarians/api/addEducation.ts, petclinic-frontend/src/pages/Vet/AddEducation.tsx, petclinic-frontend/src/pages/Vet/VetDetails.tsx, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/education/EducationServiceImpl.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/EducationServiceImplTest.java
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1373
This ticket is about allowing veterinarians and admins to add a new education onto a vet's detail page.
No, it does not change the .vscode folder.
- The addEducationToVet method is now secured with roles ADMIN and VET.
- Updated to accept vetId and Mono<EducationRequestDTO>, handling the creation of a new education record for the vet.
- Created methods for separation of concerns in the EducationServiceImpl.
- This method now calls the relevant API endpoint to add education details and returns an EducationResponseDTO wrapped in a Mono.
- Implemented the Add Education button into the front-end.
Before: 
After:
=> feat(VETS-CPC-1373): add education

api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Bills/BillResponseDTO.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillService.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillServiceImpl.java, billing-service/src/main/java/com/petclinic/billing/datalayer/Bill.java, billing-service/src/main/java/com/petclinic/billing/datalayer/BillResponseDTO.java, billing-service/src/main/java/com/petclinic/billing/util/DataSetupService.java, billing-service/src/main/java/com/petclinic/billing/util/EntityDtoUtil.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillResourceIntegrationTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/CustomerBillsControllerIntegrationTest.java, petclinic-frontend/src/features/bills/BillsListTable.tsx, petclinic-frontend/src/features/bills/models/Bill.ts
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1357
As a customer I want to be able to see the time remaining for my unpaid bills.
Acceptance criteria:
1. Customer should see the days remaining to pay their unpaid or overdue bills.
2.The time remaining should only apply to unpaid or overdue bills. PAID bills should have a bills paid or equivalent instead.
It does not.
- Changed db loader to load bills instead of bill request dtos.
- Changed bill response to have the new field time remaining.
- Changed bill response in api-gateway to have the new field time remaining. 
- Changed bill response in api-gateway to have the vet name and owner name fields.
- Fixed old tests and added new ones to the both the bill testing in the API Gateway and the Bill service.
- Added new …
=> Feat(BILL-CPC-1357): User can see time remaining to pay bill

petclinic-frontend/src/features/visits/VisitListTable.tsx
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1315)
Removing the option to add an emergency visit on the admin side because it doesn't make sense that the admin creates it. The user/customer having an emergency with their pet is the one that should create it.
No, it doesn't change it.
1. Commenting out the button on the visits table for admin
Before changes:
After changes:
=> feat(VIST-CPC-1315): remove add emergency visit on admin side.

petclinic-frontend/src/features/inventories/AddInventoryForm.tsx, petclinic-frontend/src/features/inventories/EditInventory.tsx
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1417
Everytime we want to update our inventory we must always select an image because our uploaded image input box requires a value and it doesn't already have a value. This is because logic isn't implemented to fetch the uploaded image from the database and store that value fetched into the input box. But this isn't needed thanks to this simple fix.
**No, it doesn't**
• Removed required from both the add inventory form and edit inventory form
=> bug(INVT-CPC-1417): make uploaded images not required

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/BillServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/BillController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/BillServiceClientIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/BillControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/BillControllerUnitTest.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillService.java, billing-service/src/main/java/com/petclinic/billing/businesslayer/BillServiceImpl.java, billing-service/src/main/java/com/petclinic/billing/datalayer/BillRepository.java, billing-service/src/main/java/com/petclinic/billing/presentationlayer/BillController.java, billing-service/src/test/java/com/petclinic/billing/businesslayer/BillServiceImplTest.java, billing-service/src/test/java/com/petclinic/billing/datalayer/BillServicePersistenceTests.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillControllerIntegrationTest.java, billing-service/src/test/java/com/petclinic/billing/presentationlayer/BillControllerUnitTest.java, petclinic-frontend/src/features/bills/AdminBillsListTable.tsx, petclinic-frontend/src/features/bills/api/getBillByMonth.tsx
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1351
The admin can now filter the bills by choosing a specific month and year.
No
- Added new method in the BillRepository, BillService, and BillResource to filter the bills by month
- Added a new method in the BillServiceClient, and the Bill Controller in te api-gateway
- …
=> feat(BILL-CPC-1351): Admin can filter bills by month

api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VetController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/VetControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigVetService.java, petclinic-frontend/src/features/veterinarians/api/deleteVetEducation.ts, petclinic-frontend/src/pages/Vet/DeleteVetEducation.tsx, petclinic-frontend/src/pages/Vet/VetDetails.tsx, vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java, vet-service/src/main/java/com/petclinic/vet/servicelayer/education/EducationServiceImpl.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java, vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java, vet-service/src/test/java/com/petclinic/vet/servicelayer/EducationServiceImplTest.java
JIRA:https://champlainsaintlambert.atlassian.net/browse/CPC-1374
This PR implements the functionality to delete an education entry for a veterinarian by their ID. The change addresses the need to allow users to manage veterinarians' education records more effectively, including the ability to remove outdated or incorrect entries. This enhancement improves the user experience by providing more control over the vet profiles in the system.
No, this PR does not include any changes to the .vscode folder.
Frontend:
- Added src/features/veterinarians/api/deleteVetEducation.ts to handle API calls to the backend DELETE endpoint for education …
=> feat(VETS-CPC-1374): Delete Education by Vet Id

petclinic-frontend/src/pages/Vet/VetDetails.tsx
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1418)
This PR is about changing the way the API call was coded in the VetDetails page. We have a lot of API call methods in the vetDetails page and it is bad coding practice. Each API call should be in its own separate file and should be using Axios. So I used the API call that I created in a previous PR and removed the one in VetDetails page.  
This PR does not effect the .vscode file
- Removed the API call from the VetDetails page.
- Created a method that would call the fetchVetPhoto API call from the fetchPhoto.ts file
Before:
After:
=> bug/(VETS-CPC-1418): fix code for get photos

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, petclinic-frontend/src/features/visits/Emergency/Api/getAllEmergency.ts, petclinic-frontend/src/features/visits/api/getAllVisits.ts
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1572)
The  visits table was getting errors when trying to fetch visits and emergency visits. 
No
- Changed the axios version of getAllVisits and getAllEmergency to V2
- Removed the unused getAllVisits from api gateway V1
- Removed the incorrect data parsing in getAllEmergency 
- Backend was returning a JSON and frontend was expecting a stream
No it does not
No it does not
Before
After
=> bug(VIST-CPC-1572): fixed the apI fetch of get list getallvisits.ts and getallemergency.ts

petclinic-frontend/src/features/inventories/InventoryProducts.css
**JIRA:**
https://champlainsaintlambert.atlassian.net/browse/CPC-1465
The ticket is about fixing the UI when translating to other languages, specifically when translating into certain languages, some texts don't fully show up which cuts off some words. Also when using the edit or move button, when brought to their respective page, the translation formatting is also bad there. We are doing this change to make the UI cleaner whether it's in english or any other translated language for a better overall user experience.
No.
- The only file changed was InventoryProducts.css. 
- Allowed table headers (<th>) and cells (<td>) to wrap/break text so translated French/German/Spanish labels don’t overflow.
- Added column-specific widths (Supply Id, Supply Name, Description, etc.).
- Overrode fixed …
=> bug(INVT-CPC-1465): Fix translation formatting

petclinic-frontend/src/pages/FAQ/FAQ.tsx, petclinic-frontend/src/pages/Home/Home.tsx
**JIRA:** [link](https://champlainsaintlambert.atlassian.net/browse/CPC-1598)
This ticket simple fixes the slight styling issue with the home page where the contact band had misplaced components. This was simply a bug that I thought needed to be addressed in this specific sprint. I also took this opportunity to spice up the FAQ page with a small additional animation.
No changes to `.vscode`.
- **Home:** Fixed the contact band by fixing column seperation and adding better bootstrap classes + xs.
- **FAQ:** Added more animation using the Reveal component created in a separate ticket.
No changes to any API calls.
No. Reuses existing endpoints; no new service-to-service calls. (No C4 L2 updates required.)
**Before:**
**After:**
=> bug(AUTH-CPC-1598): Homepage contact band buttons are misplaced

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v1/InventoryControllerV1.java, api-gateway/src/main/resources/static/scripts/Inventory-form/inventory-form.controller.js, api-gateway/src/main/resources/static/scripts/inventory-update-form/inventory-update-form.js, petclinic-frontend/src/features/inventories/InventoriesListTable.tsx, petclinic-frontend/src/shared/models/path.routes.ts
JIRA: link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1601)
Context:
The ticket is about allowing when you add an inventory to be able to choose an inventory type. It was needed because in the Angular FE it was not possible to fetch the endpoint to get all types in the add inventory form. It was also necessary to fix the update inventory endpoint in the react FE because the url was not following the conventions.
Does this PR change the .vscode folder in petclinic-frontend?:
No.
Reviewers need to check for any changes to the .vscode folder and add a comment about it to their review comments.
Changes
1. Change the url in inventory-form-controller.js to $http.get("api/gateway/inventories/types")
2. Change the url of EditInventory = …
=> Bug(INVT-CPC-1601): Fix Get All Types In Angular Frontend

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/PetController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/PetControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigCustomersService.java, docker-compose_no_FE.yml, petclinic-frontend/src/features/customers/api/deletePet.ts, petclinic-frontend/src/features/customers/components/UpdatePetForm.tsx, petclinic-frontend/src/pages/Customer/ProfilePage.css, petclinic-frontend/src/pages/Customer/ProfilePage.tsx
https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/14?label=CUST&selectedIssue=CPC-1611
This PR addresses the issue that an owner cannot delete his pet or his pet information. In the Owner Profile tab he is now able to go in the pet section and easily delete his pet.
No it does not.
- Added a button on the front end and the code that goes with it to be able to delete your own pet.
Yes it does since a V1 version of delete pet existed but was deprecated
No it does not.
=> feat(CUST-CPC-1611): Delete Pet

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v1/VisitsControllerV1.java, api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VisitController.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/visit/VisitControllerIntegrationTest.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/visit/VisitControllerUnitTest.java, petclinic-frontend/src/features/visits/Emergency/Api/addEmergency.ts, petclinic-frontend/src/features/visits/Emergency/Api/deleteEmergency.ts, petclinic-frontend/src/features/visits/Emergency/Api/getAllEmergency.ts, petclinic-frontend/src/features/visits/Emergency/Api/getEmergencyById.ts, petclinic-frontend/src/features/visits/Emergency/Api/getEmergencyVisitsByOwnerId.ts, petclinic-frontend/src/features/visits/Emergency/Api/updateEmergency.ts, petclinic-frontend/src/features/visits/Review/Api/addCustomerReview.ts, petclinic-frontend/src/features/visits/Review/Api/addReview.ts, petclinic-frontend/src/features/visits/Review/Api/editReview.ts, petclinic-frontend/src/features/visits/Review/Api/getAllReviews.ts, petclinic-frontend/src/features/visits/Review/Api/getReview.ts, petclinic-frontend/src/features/visits/VisitListTable.tsx, petclinic-frontend/src/features/visits/api/addVisit.ts, petclinic-frontend/src/features/visits/api/exportVisitsCSV.ts, petclinic-frontend/src/features/visits/api/getAllOwnerVisits.ts, petclinic-frontend/src/features/visits/api/getAllVisits.ts, petclinic-frontend/src/features/visits/api/updateVisit.ts, petclinic-frontend/src/shared/models/path.routes.ts, visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitController.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java, visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitControllerUnitTest.java
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1519)
This PR focuses on refactoring and stabilizing the visits module across the API Gateway and frontend. The goal is to centralize all visit-related logic into dedicated controllers, ensure frontend calls are consistent with backend endpoints, and improve maintainability by consolidating tests.
No
Refactored visits endpoints
- Moved all visit-related endpoints into a new controller in the new V1 folder so they can be used by …
=> bug(VIST-CPC-1519): refractored endpoints to V1

api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v1/CartControllerV1.java, api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v1/Cart/CartControllerV1UnitTest.java, petclinic-frontend/src/features/carts/components/CartTable.tsx, petclinic-frontend/src/layouts/AppNavBar.tsx
**JIRA:**
[Jira link](https://champlainsaintlambert.atlassian.net/browse/CPC-1711?atlOrigin=eyJpIjoiNmI4NTMxODk0MjAyNDllNTk2MzM1MTVkZjY3N2E2N2QiLCJwIjoiaiJ9)
Allowing admin to access certain customer endpoints because as an admin in case something goes wrong they should be able to, for example, retrieve a cart. This issue is important because there's also an api call to cart in the navbar which only allowed owners to call, so when an admin tried to log in they would be met with 403 Forbidden.
No
- Added Admin as an allowed role for certain endpoints in CartControllerV1
- Added missing tests for moveAllWishlistToCart for 90% coverage for CartControllerV1
- Updated AppNavBar and CartTable for improved cart visibility for admin
No
No
No UI changes
=> bug(CART-CPC-1711): Add admin access to certain endpoints in CartControllerV1

petclinic-frontend/src/features/inventories/InventoryProducts.tsx, petclinic-frontend/src/features/inventories/MoveInventoryProducts.tsx, petclinic-frontend/src/features/inventories/api/moveInventoryProduct.ts, petclinic-frontend/src/shared/models/path.routes.ts
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1607
Allow inventory managers to move products between inventory types and cancel the operation from the move dialog. Fixes an axios PUT call so the request config is passed correctly.
No
- Added `undefined` as the PUT body in `moveInventoryProducts.ts` so that the config arg `{ useV2: false }` is passed correctly in the axios.put
- Added a cancel button to `moveInventoryProducts.tsx` 
- Updated the endpoint URL to be fully RESTful (removed redundant `/move`).
No
No
Before (no cancel button):
After:
=> bug(INVT-CPC-1607): fix move button in supply list
